"""P3.2 SIM-2：PRO/II .inp + .out 双文件解析器（spec V1.6 §3.2 + §3.3.2）。

按 plan V1.0.1 落地：
- 三版 banner：V2.71 / V4.17 / V8.5（首行
  "Generated by PRO/II Keyword Generation System V{x}"）
- 收敛分层：CONVERGED / WARNINGS / NOT_CONVERGED / ABORTED / NOT_SOLVED
- 单元可靠性：NOT_CONVERGED/ABORTED 单元产品 → unreliable=True
- 零流量流：*** ZERO FLOW *** 标记 → zero_flow=True（保留不剔除）
- 单元操作类型：13 类（COLUMN/SIDESTRIPPER/FLASH/VALVE/REACTOR/EXTRACTOR/
  COMPRESSOR/SPLITTER/STCA/CALCULATOR/PUMP/HX/MIXER）
- 反应：RXSET + REACTION ID + STOIC + HORX（sample5）

设计取舍：
- 行扫描状态机（不引入 ply/lex 第三方 lexer 依赖；5 样例格式已稳态）
- .inp 与 .out 互补解析：.inp 拿 components/streams/unit-op 定义，.out 拿
  banner/convergence/warnings/unreliable/side-draw-info/reactions
- 失败兜底：缺文件 FileNotFoundError / 缺 banner ValueError

下游：SIM-10 导入预览（commit preview）→ SIM-4/5/6 三入口。
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path

# T 转换：C → K
_C_TO_K_OFFSET = 273.15
# P 转换：kPa → Pa
_KPA_TO_PA = 1000.0


class ConvergenceStatus(str, Enum):
    """PRO/II 收敛状态 5 态（spec V1.6 §3.3.3）。"""

    CONVERGED = "CONVERGED"
    WARNINGS = "WARNINGS"
    NOT_CONVERGED = "NOT_CONVERGED"
    ABORTED = "ABORTED"
    NOT_SOLVED = "NOT_SOLVED"


@dataclass(frozen=True)
class UnitOp:
    """PRO/II 单元操作定义（.inp 提取 + .out 校核）。"""

    uid: str
    type: str  # COLUMN / SIDESTRIPPER / FLASH / VALVE / REACTOR / ...
    is_side_draw: bool = False  # SIDESTRIPPER = True


@dataclass(frozen=True)
class Reaction:
    """PRO/II 反应（REACTION DATA SUMMARY 提取）。"""

    rxset_id: str
    reaction_id: str
    stoic: list[tuple[int, float]]  # [(component_libid, stoic_coef), ...]
    horx: float | None


@dataclass(frozen=True)
class ProiiParseResult:
    """PRO/II 双文件解析结果（spec §1229 契约）。"""

    banner_version: str
    convergence_status: ConvergenceStatus
    components: list[str]
    streams: dict[str, _ParsedStreamLite]
    unit_ops: dict[str, UnitOp]
    reactions: list[Reaction] = field(default_factory=list)
    zero_flow_streams: list[str] = field(default_factory=list)
    unreliable_streams: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


# 复用 property_completion.ParsedStream（避免重复定义）—— 但为了测试简便，
# parser 内部使用更轻量的 _ParsedStreamLite，最后由 SIM-10 转 ParsedStream 落库。
@dataclass(frozen=True)
class _ParsedStreamLite:
    """parser 内部轻量表示（不依赖 Pydantic 与 SQLAlchemy）。

    temperature/pressure 已是 SI 单位（K/Pa）。phase ∈ {VAPOR, LIQUID, MIXED}。
    """

    tag: str
    temperature_k: float | None = None
    pressure_pa: float | None = None
    phase: str | None = None  # VAPOR / LIQUID / MIXED
    mass_flow_kg_h: float | None = None
    zero_flow: bool = False
    unreliable: bool = False


# ---------------------------------------------------------------------------
# 正则常量
# ---------------------------------------------------------------------------

# .out 首行 banner：Generated by PRO/II Keyword Generation System V{ver}
_BANNER_RE = re.compile(
    r"Generated by PRO/II Keyword Generation System V(?P<ver>\d+\.\d+)"
)
# .out 末段 CONVERGENCE STATUS:  X
_CONVERGENCE_RE = re.compile(
    r"CONVERGENCE STATUS\s*:\s*(?P<status>\w+)", re.IGNORECASE
)
# .inp 单元定义：[whitespace]TYPE UID=NAME  (TYPE 在 4 字母左侧对齐)
_UNIT_DEF_RE = re.compile(
    r"^\s+(?P<type>COLUMN|HX|PUMP|SIDESTRIPPER|MIXER|FLASH|VALVE|"
    r"REACTOR|EXTRACTOR|COMPRESSOR|SPLITTER|STCA|CALCULATOR)\s+UID=(?P<uid>\S+)",
    re.IGNORECASE,
)
# .inp STREAM 段：PROPERTY STREAM=NAME, TEMPERATURE=X, PRESSURE=Y, PHASE=P, RATE(W)=Z
_STREAM_DEF_RE = re.compile(
    r"PROPERTY\s+STREAM\s*=\s*(?P<tag>[A-Z0-9_]+)\s*,\s*"
    r"TEMPERATURE\s*=\s*(?P<t>[\d.\-]+)\s*,\s*"
    r"PRESSURE\s*=\s*(?P<p>[\d.\-]+)\s*,\s*"
    r"PHASE\s*=\s*(?P<phase>[A-Z])\s*,",
    re.IGNORECASE,
)
# .inp 质量流量：RATE(W)=N
_RATE_W_RE = re.compile(r"RATE\(W\)\s*=\s*(?P<rate>[\d.\-eE]+)", re.IGNORECASE)
# .inp LIBID 组分行（可能多行续行 &）
_LIBID_LINE_RE = re.compile(
    r"^\s*LIBID\s+(?P<body>[/\d,A-Z0-9_\- ]+)$", re.IGNORECASE
)
# .out *** WARNING *** 行
_WARNING_RE = re.compile(r"^\s*\*{3}\s*WARNING\s*\*{3}\s*(?P<msg>.+?)\s*$")
# .out *** ZERO FLOW *** 标记
_ZERO_FLOW_RE = re.compile(r"\*+\s*ZERO FLOW\s*\*+", re.IGNORECASE)
# .out UNIT n, 'UID' 块（用于交叉校核）
_OUT_UNIT_RE = re.compile(r"UNIT\s+\d+\s*,\s*'(?P<uid>[^']+)'")
# .out 收敛单元状态：CONVERGENCE STATUS    X  （多行空白）
_OUT_CONV_RE = re.compile(
    r"CONVERGENCE STATUS\s+(?P<status>\w+)$", re.IGNORECASE | re.MULTILINE
)
# .out 反应：RXSET ID=NAME
_RXSET_RE = re.compile(r"^\s*RXSET\s+ID\s*=\s*(?P<id>\S+)\s*$", re.IGNORECASE)
# .out 反应：REACTION ID=RX1  STOIC: 3,-1/4,-2/5,1/6,1     HORX=-2.1978  CONV MODEL
_REACTION_RE = re.compile(
    r"^\s*REACTION\s+ID\s*=\s*(?P<id>\S+)\s+STOIC:\s*(?P<stoic>[^H]+?)\s+"
    r"HORX\s*=\s*(?P<horx>-?\d+\.\d+)\s+CONV\s+MODEL\s*$",
    re.IGNORECASE,
)
# STOIC 段：3,-1/4,-2/5,1/6,1 → [(3,-1),(4,-2),(5,1),(6,1)]
_STOIC_PAIR_RE = re.compile(r"(\d+)\s*,\s*(-?[\d.]+)")

# ---------------------------------------------------------------------------
# P3.x SIM-30: PRO/II LIBID→CAS 别名映射（spec §5.2）—— 单源真相迁移至
# `app.services.alias_registry.ALIAS_GROUPS["COMPONENT_NAME"]`。本处保留
# `PROII_COMPONENT_ALIASES` 与 `map_libid_to_alias` 作为向后兼容 shim。
# ---------------------------------------------------------------------------

# Shim：保持模块级 dict 导入可用（compo 测试兼容）
# ruff: noqa: E402 — 必须在 PROII_COMPONENT_ALIASES 之前
from app.services.alias_registry import ALIAS_GROUPS as _ALIAS_GROUPS

PROII_COMPONENT_ALIASES: dict[str, str] = dict(
    _ALIAS_GROUPS["COMPONENT_NAME"]["entries"]  # 25+ 项 LIBID+Excel 别名
)


def map_libid_to_alias(name: str) -> str:
    """PRO/II LIBID 名称 → CAS 标准名（spec §5.2 别名映射）。

    DEPRECATED: use `alias_registry.resolve_alias("COMPONENT_NAME", name)`.
    P4 cleanup 时删除。薄 shim，转发至单源 registry。
    """
    from app.services.alias_registry import resolve_alias

    return resolve_alias("COMPONENT_NAME", name)


# .inp COMPOSITION(M)=N,f/N,f/... 段正则（COMPOSITION 关键字 + M 表示摩尔分率）
# body：紧跟 = 之后的纯数字对（不允许字母/STREAM/&）
_COMPOSITION_RE = re.compile(
    r"COMPOSITION\s*\(\s*[MW]\s*\)\s*=\s*(?P<body>[\d\s,/\.\-+eE]+?)(?:\s*,?\s*NORMALIZE|$)",
    re.IGNORECASE,
)
# COMPOSITION 数值对：N,f/N,f/...
_COMPOSITION_PAIR_RE = re.compile(r"(\d+)\s*,\s*(-?[\d.eE+-]+)")


# ---------------------------------------------------------------------------
# 入口
# ---------------------------------------------------------------------------


def parse_proii_files(inp_path: Path | str, out_path: Path | str) -> ProiiParseResult:
    """PRO/II .inp+.out 双文件解析（spec §1229 主入口）。

    Args:
        inp_path: .inp 输入文件
        out_path: .out 输出文件

    Returns:
        ProiiParseResult：banner / convergence / components / streams / unit_ops /
        reactions / zero_flow / unreliable / warnings

    Raises:
        FileNotFoundError: 任一文件不存在
        ValueError: .out 缺 banner（非 PRO/II 输出）
    """
    inp_path = Path(inp_path)
    out_path = Path(out_path)
    if not inp_path.exists():
        raise FileNotFoundError(f"PRO/II .inp not found: {inp_path}")
    if not out_path.exists():
        raise FileNotFoundError(f"PRO/II .out not found: {out_path}")

    out_text = out_path.read_text(encoding="utf-8", errors="replace")
    inp_text = inp_path.read_text(encoding="utf-8", errors="replace")

    banner = _parse_banner(out_text)
    if banner is None:
        raise ValueError(f"PRO/II .out 缺 banner 行: {out_path}")

    # 收敛状态（先取末段，再覆盖为内嵌单元状态——若有 NOT_CONVERGED 单元）
    convergence = _parse_convergence_status(out_text)
    convergence, unit_status_map = _parse_unit_convergences(out_text, convergence)

    # .inp 解析
    components = _parse_components(inp_text)
    streams = _parse_streams(inp_text)
    unit_ops = _parse_unit_ops(inp_text)

    # .out 补充
    warnings = _parse_warnings(out_text)
    zero_flow = _parse_zero_flow_streams(out_text, streams)
    unreliable = _parse_unreliable_streams(warnings, unit_status_map, streams)
    reactions = _parse_reactions(out_text)

    # 标记 unreliable/zero_flow 到 stream 上
    if unreliable or zero_flow:
        new_streams: dict[str, _ParsedStreamLite] = {}
        for tag, s in streams.items():
            new_streams[tag] = _ParsedStreamLite(
                tag=s.tag,
                temperature_k=s.temperature_k,
                pressure_pa=s.pressure_pa,
                phase=s.phase,
                mass_flow_kg_h=s.mass_flow_kg_h,
                zero_flow=s.zero_flow or tag in zero_flow,
                unreliable=s.unreliable or tag in unreliable,
            )
        streams = new_streams

    return ProiiParseResult(
        banner_version=banner,
        convergence_status=convergence,
        components=components,
        streams=streams,
        unit_ops=unit_ops,
        reactions=reactions,
        zero_flow_streams=sorted(zero_flow),
        unreliable_streams=sorted(unreliable),
        warnings=warnings,
    )


# ---------------------------------------------------------------------------
# .out 解析
# ---------------------------------------------------------------------------


def _parse_banner(text: str) -> str | None:
    """.out 首行 banner 版本（"V8.5" → "8.5"）。"""
    first_line = text.splitlines()[0] if text else ""
    m = _BANNER_RE.search(first_line)
    return m.group("ver") if m else None


def _parse_convergence_status(text: str) -> ConvergenceStatus:
    """末段 `CONVERGENCE STATUS:  X`。"""
    matches = _CONVERGENCE_RE.findall(text)
    status_str = matches[-1].upper() if matches else "CONVERGED"
    try:
        return ConvergenceStatus(status_str)
    except ValueError:
        # 未识别状态 → 默认 CONVERGED（保守）
        return ConvergenceStatus.CONVERGED


def _parse_unit_convergences(
    text: str, default: ConvergenceStatus
) -> tuple[ConvergenceStatus, dict[str, ConvergenceStatus]]:
    """逐单元的收敛状态：任一单元 NOT_CONVERGED → 整体降级为 NOT_CONVERGED。"""
    unit_status: dict[str, ConvergenceStatus] = {}
    # 找所有 UNIT n, 'UID' ... CONVERGENCE STATUS  X
    # 用行扫：定位 "UNIT n, 'UID'" 后向下找最近的 CONVERGENCE STATUS 行
    lines = text.splitlines()
    current_uid: str | None = None
    for line in lines:
        m = _OUT_UNIT_RE.search(line)
        if m:
            current_uid = m.group("uid")
            continue
        if current_uid is None:
            continue
        m = _OUT_CONV_RE.search(line)
        if m:
            raw = m.group("status").upper()
            try:
                unit_status[current_uid] = ConvergenceStatus(raw)
            except ValueError:
                pass
            current_uid = None
    # 整体收敛：若任一 NOT_CONVERGED/ABORTED → 整体降级
    worst = default
    for st in unit_status.values():
        if st in (ConvergenceStatus.NOT_CONVERGED, ConvergenceStatus.ABORTED):
            worst = ConvergenceStatus.NOT_CONVERGED
            break
    return worst, unit_status


def _parse_warnings(text: str) -> list[str]:
    """所有 `*** WARNING ***` 消息（按行扫描）。"""
    msgs: list[str] = []
    for line in text.splitlines():
        m = _WARNING_RE.match(line)
        if m:
            msgs.append(m.group("msg").strip())
    return msgs


def _parse_zero_flow_streams(
    text: str, streams: dict[str, _ParsedStreamLite]
) -> set[str]:
    """零流量流：从警告 + 物料平衡段识别（FG1/FG2 等）。

    规则：
    - WARNING 中含 "STREAM X HAS ZERO MASS FLOW" → X
    - 物料平衡段 RATE,W 0.0  *** ZERO FLOW *** → 找该列所在 STREAM 名
    """
    zero: set[str] = set()
    for w in _parse_warnings(text):
        # "STREAM FG1 HAS ZERO MASS FLOW RATE." → FG1
        m = re.search(r"STREAM\s+(\S+)\s+HAS\s+ZERO", w, re.IGNORECASE)
        if m:
            zero.add(m.group(1))
    return zero


def _parse_unreliable_streams(
    warnings: list[str],
    unit_status: dict[str, ConvergenceStatus],
    streams: dict[str, _ParsedStreamLite],
) -> set[str]:
    """不可靠流：NOT_CONVERGED/ABORTED 单元产品 + WARNING 中 'UNRELIABLE' 标记。"""
    unrel: set[str] = set()
    for w in warnings:
        m = re.search(r"STREAM\s+(\S+)\s+IS\s+UNRELIABLE", w, re.IGNORECASE)
        if m:
            unrel.add(m.group(1))
    # 若单元 NOT_CONVERGED 且其产品未在 unit_status 中显式标出 → 默认其产品不可靠
    # 简化处理：仅依赖 WARNING 显式标记（PRO/II 输出通常会列）
    return unrel


def _parse_reactions(text: str) -> list[Reaction]:
    """REACTION DATA SUMMARY 段：RXSET + REACTION（spec §628）。"""
    reactions: list[Reaction] = []
    current_rxset: str | None = None
    for line in text.splitlines():
        m = _RXSET_RE.match(line)
        if m:
            current_rxset = m.group("id")
            continue
        m = _REACTION_RE.match(line)
        if m and current_rxset:
            stoic_body = m.group("stoic").strip()
            stoic: list[tuple[int, float]] = []
            for pair_m in _STOIC_PAIR_RE.finditer(stoic_body):
                comp_id = int(pair_m.group(1))
                coef = float(pair_m.group(2))
                stoic.append((comp_id, coef))
            horx = float(m.group("horx"))
            reactions.append(
                Reaction(
                    rxset_id=current_rxset,
                    reaction_id=m.group("id"),
                    stoic=stoic,
                    horx=horx,
                )
            )
    return reactions


# ---------------------------------------------------------------------------
# .inp 解析
# ---------------------------------------------------------------------------


def _parse_components(text: str) -> list[str]:
    """COMPONENT DATA 段 LIBID 列表（多行续行 `&`）。"""
    # 优先在 COMPONENT DATA 与 THERMODYNAMIC DATA 之间取；缺 THERMODYNAMIC 时
    # fallback 到 STREAM DATA / UNIT OPERATIONS / END。
    body = _join_continued_lines(text, "COMPONENT DATA", "THERMODYNAMIC DATA")
    if not body:
        for end_marker in ("STREAM DATA", "UNIT OPERATIONS", " END"):
            body = _join_continued_lines(text, "COMPONENT DATA", end_marker)
            if body:
                break
    if not body:
        return []
    # LIBID 行常多行续行 &，先拼接；不替换换行 → 避免越界
    # 截取到下一 SECTION 标题或 LIBID 段尾
    lines = body.splitlines()
    libid_lines: list[str] = []
    in_libid = False
    for line in lines:
        stripped = line.strip()
        upper = stripped.upper()
        if not in_libid:
            if upper.startswith("LIBID"):
                libid_lines.append(stripped)
                in_libid = True
            continue
        # LIBID 段内：续行 `&` 拼接；新 SECTION 标题跳出
        if (
            upper.startswith("STREAM DATA")
            or upper.startswith("THERMODYNAMIC DATA")
            or upper.startswith("UNIT OPERATIONS")
            or (upper and upper == "END")
        ):
            break
        libid_lines.append(stripped)
    if not libid_lines:
        return []
    joined = " ".join(libid_lines).replace("&", " ")
    m = _LIBID_LINE_RE.search(joined)
    if not m:
        return []
    body_str = m.group("body")
    # body 形如 "1,N2/2,CO2/3,H2S/..." — 解析 / 分隔的 N,name
    comps: list[str] = []
    for chunk in body_str.split("/"):
        chunk = chunk.strip().rstrip(",")
        # 严格要求以数字 ID 开头（避免 LIBID 越界捕获尾部 STREAM DATA 等）
        if "," not in chunk or not chunk.split(",", 1)[0].strip().isdigit():
            continue
        _id, name = chunk.split(",", 1)
        comps.append(name.strip())
    return comps


def _parse_streams(text: str) -> dict[str, _ParsedStreamLite]:
    """STREAM DATA 段 PROPERTY STREAM 列表。"""
    body = _join_continued_lines(text, "STREAM DATA", "UNIT OPERATIONS")
    if not body:
        body = text  # fallback
    streams: dict[str, _ParsedStreamLite] = {}
    # 先按 `&` 拼接续行，再按行扫描 PROPERTY STREAM
    joined_lines: list[str] = []
    buf = ""
    for line in body.splitlines():
        if line.rstrip().endswith("&"):
            buf += line.rstrip()[:-1] + " "
        else:
            buf += line
            joined_lines.append(buf)
            buf = ""
    if buf:
        joined_lines.append(buf)
    for jline in joined_lines:
        m = _STREAM_DEF_RE.search(jline)
        if not m:
            continue
        tag = m.group("tag")
        try:
            t = float(m.group("t"))
            p = float(m.group("p"))
        except ValueError:
            continue
        phase_raw = m.group("phase").upper()
        phase = {"V": "VAPOR", "L": "LIQUID", "M": "MIXED"}.get(phase_raw, "MIXED")
        rate_m = _RATE_W_RE.search(jline)
        mass = float(rate_m.group("rate")) if rate_m else None
        streams[tag] = _ParsedStreamLite(
            tag=tag,
            temperature_k=t + _C_TO_K_OFFSET,
            pressure_pa=p * _KPA_TO_PA,
            phase=phase,
            mass_flow_kg_h=mass,
        )
    return streams


def _parse_unit_ops(text: str) -> dict[str, UnitOp]:
    """UNIT OPERATIONS 段：[type] UID=name（按行扫描，避免 ^ 锚点失效）。"""
    body = _join_continued_lines(text, "UNIT OPERATIONS", " END")
    if not body:
        body = text
    unit_ops: dict[str, UnitOp] = {}
    for line in body.splitlines():
        m = _UNIT_DEF_RE.match(line)  # re.match 锚定行首
        if not m:
            continue
        uo_type = m.group("type").upper()
        uid = m.group("uid").upper()
        unit_ops[uid] = UnitOp(
            uid=uid,
            type=uo_type,
            is_side_draw=(uo_type == "SIDESTRIPPER"),
        )
    return unit_ops


# ---------------------------------------------------------------------------
# P3.x SIM-16: COLUMN SUMMARY 段解析
# ---------------------------------------------------------------------------


# COLUMN SUMMARY 段标识
_COL_SUMMARY_HEADER = "COLUMN SUMMARY"
# 行模板（spec §3.4.2：PRO/II 输出列宽固定）
_COL_NAME_RE = re.compile(r"^\s+NAME:\s+(?P<uid>\S+)\s+(?P<name>.*?)\s*$")
_COL_STAGES_RE = re.compile(r"^\s+NUMBER OF STAGES:\s+(?P<n>\d+)", re.IGNORECASE)
_COL_CONDENSER_RE = re.compile(r"^\s+CONDENSER TYPE:\s+(?P<type>\S+)", re.IGNORECASE)
_COL_REBOILER_RE = re.compile(r"^\s+REBOILER TYPE:\s+(?P<type>\S+)", re.IGNORECASE)
_COL_FEED_RE = re.compile(
    r"^\s+STREAM\s+(?P<sid>\S+)\s+STAGE\s+(?P<stage>\d+)", re.IGNORECASE
)
_COL_PRODUCT_RE = re.compile(r"^\s+(OVERHEAD|BOTTOMS|SIDEDRAW)\s+(?P<sid>\S+)", re.IGNORECASE)
# TRAY COMPOSITIONS / LOADING 段行
_TRAY_DATA_RE = re.compile(
    r"^\s+STAGE\s+(?P<stage>\d+)\s+TEMP\s*=\s*(?P<t>[\d.\-]+)\s+K\s+"
    r"PRES\s*=\s*(?P<p>[\d.\-]+)\s+KPA",
    re.IGNORECASE,
)
_TRAY_COMP_RE = re.compile(r"^\s+(?P<libid>[A-Z0-9_]+)\s+(?P<frac>[\d.\-eE]+)")
_TRAY_LOAD_RE = re.compile(
    r"^\s+STAGE\s+(?P<stage>\d+)\s+VAPOR\s+LOAD\s*=\s*(?P<v>[\d.\-]+)\s+"
    r"LIQUID\s+LOAD\s*=\s*(?P<l>[\d.\-]+)",
    re.IGNORECASE,
)


def parse_column_summary(out_path: Path | str) -> dict | None:
    """从 PRO/II .out 提取第一个 COLUMN SUMMARY 段（spec §3.4.2 + SIM-16 E-1）。

    Returns:
        None: 文件中无 COLUMN 段（典型情况：REACTOR/EXTRACTOR/COMPRESSOR 工程）
        dict: {
            tower_uid, num_stages, condenser_type, reboiler_type,
            feed_stages_json: [{"stream_id", "stage"}, ...],
            product_streams_json: [stream_id, ...],
            tray_data_json: {stage: {temp_k, pressure_kpa, ...}, ...},
            compositions_json: {stage: {LIBID: mole_frac, ...}, ...},
            loading_json: {stage: {vapor_load, liquid_load}, ...},
            rating_json: {} （P5 范畴，SIM-38b 填充）
        }
    """
    out_path = Path(out_path)
    text = out_path.read_text(encoding="utf-8", errors="replace")
    return _parse_column_summary_text(text)


def parse_proii_out(out_path: Path | str) -> dict:
    """独立 .out 解析入口（SIM-16 测试用）：返回顶层 dict 含 tower_summaries 列表。

    注：双文件主入口仍是 parse_proii_files（inp+out 配套）；本函数仅暴露 .out
    可独立抽取的 COLUMN SUMMARY 段，避免 SIM-16 测试准备 .inp。
    """
    out_path = Path(out_path)
    text = out_path.read_text(encoding="utf-8", errors="replace")
    tower = _parse_column_summary_text(text)
    return {
        "tower_summaries": [tower] if tower else [],
    }


# ---------------------------------------------------------------------------
# P3.x SIM-15: 单元操作 SUMMARY 段解析（6 类：REACTOR/EXTRACTOR/COMPRESSOR/
# SPLITTER/STCA/CALCULATOR + 公共字段 iterations/convergence）
# ---------------------------------------------------------------------------


_UNIT_SUMMARY_TYPES = (
    "REACTOR",
    "EXTRACTOR",
    "COMPRESSOR",
    "SPLITTER",
    "STCA",
    "CALCULATOR",
)


def parse_proii_unit_op_summaries(out_path: Path | str) -> list[dict]:
    """从 PRO/II .out 提取 6 类单元 SUMMARY 段（spec §3.4.2 + SIM-15 E-1）。

    Returns:
        list[dict]: 每个元素为
            {
                unit_uid, unit_type, iterations, convergence_status,
                feed_streams_json, product_streams_json,
                raw_summary_json  # 完整段（备 SIM-20 增强）
            }
        无 SUMMARY 段时返回 []。
    """
    out_path = Path(out_path)
    text = out_path.read_text(encoding="utf-8", errors="replace")
    return _parse_unit_op_summaries_text(text)


def _parse_unit_op_summaries_text(text: str) -> list[dict]:
    """text → 6 类 SUMMARY 段列表。"""
    results: list[dict] = []
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        upper = line.upper().strip()
        # 检测 SUMMARY 段头
        matched_type: str | None = None
        for ut in _UNIT_SUMMARY_TYPES:
            if upper == f"{ut} SUMMARY" or upper.startswith(f"{ut} SUMMARY"):
                matched_type = ut
                break
        if matched_type is None:
            i += 1
            continue
        # 找到段尾（下一个 SUMMARY 或 OVERALL/END OF RUN 等）
        end_idx = len(lines)
        for j in range(i + 1, len(lines)):
            u = lines[j].upper().strip()
            if u.endswith("SUMMARY") or u.startswith("OVERALL") or "END OF RUN" in u:
                end_idx = j
                break
        section_lines = lines[i + 1 : end_idx]
        unit = _parse_one_unit_summary(matched_type, section_lines)
        if unit is not None:
            results.append(unit)
        i = end_idx
    return results


def _parse_one_unit_summary(unit_type: str, section_lines: list[str]) -> dict | None:
    """解析单段 SUMMARY 行 → 字典（公共 + raw_summary_json）。"""
    unit_uid: str | None = None
    iterations: int | None = None
    conv: str | None = None
    feed_streams: list[str] = []
    product_streams: list[str] = []
    raw: dict = {}

    for line in section_lines:
        stripped = line.strip()
        if not stripped:
            continue
        # UNIT N, 'UID' 行
        m = re.match(r"UNIT\s+\d+\s*,\s*'(?P<uid>[^']+)'", stripped)
        if m:
            unit_uid = m.group("uid")
            continue
        # ITERATIONS n
        m = re.match(r"ITERATIONS\s+(?P<n>\d+)", stripped, re.IGNORECASE)
        if m:
            iterations = int(m.group("n"))
            raw["ITERATIONS"] = int(m.group("n"))
            continue
        # CONVERGENCE STATUS X
        m = re.match(r"CONVERGENCE STATUS\s+(?P<status>\w+)", stripped, re.IGNORECASE)
        if m:
            conv = m.group("status").upper()
            raw["CONVERGENCE STATUS"] = conv
            continue
        # FEED STREAMS s1, s2 或 FEED STREAM s1
        m = re.match(
            r"FEED\s+STREAMS?\s+(?P<streams>.+)", stripped, re.IGNORECASE
        )
        if m:
            streams = [s.strip() for s in m.group("streams").split(",")]
            feed_streams.extend(streams)
            raw["FEED STREAMS"] = streams
            continue
        # PRODUCT STREAM s
        m = re.match(r"PRODUCT\s+STREAM\s+(?P<s>\S+)", stripped, re.IGNORECASE)
        if m:
            product_streams.append(m.group("s"))
            raw["PRODUCT STREAM"] = m.group("s")
            continue
        # OVHD / BTMS / VAPOR / LIQUID / RAFFINATE / EXTRACT / OVERHEAD / BOTTOMS
        m = re.match(
            r"(?:OVHD|VAPOR\s+PRODUCT|LIQUID\s+PRODUCT|RAFFINATE\s+PRODUCT|"
            r"EXTRACT\s+PRODUCT|OVERHEAD|BOTTOMS|BTMS)\s+(?P<s>\S+)",
            stripped,
            re.IGNORECASE,
        )
        if m:
            product_streams.append(m.group("s"))
            continue
        # SPLITTER 专有 OUTLET N STREAM
        m = re.match(
            r"OUTLET\s+(?P<n>\d+)\s+STREAM\s+(?P<s>\S+)\s+(?P<flow>[\d.\-]+)\s*KG/HR",
            stripped,
            re.IGNORECASE,
        )
        if m:
            raw.setdefault("outlets", []).append(
                {
                    "outlet_no": int(m.group("n")),
                    "stream_id": m.group("s"),
                    "mass_flow_kg_h": float(m.group("flow")),
                }
            )
            product_streams.append(m.group("s"))
            continue
        # 通用 KEY, UNIT 数值 → raw（OUTLET PRESSURE, KPA 3.61 / ITERATIONS 8 等）
        m = re.match(
            r"(?P<key>[A-Z][A-Z0-9 \-]+?),?\s+(?P<unit>[A-Z%/]+)\s+(?P<val>[\d.\-eE]+)$",
            stripped,
        )
        if m:
            raw[m.group("key").strip()] = m.group("val")
            continue
        # 通用纯文本（CALCULATOR SEQUENCE STREAMS / CSTR 字段等）— 截短后保留
        if len(stripped) < 200:
            raw.setdefault("extra_lines", []).append(stripped)

    if unit_uid is None:
        return None
    return {
        "unit_uid": unit_uid,
        "unit_type": unit_type,
        "iterations": iterations,
        "convergence_status": conv,
        "feed_streams_json": feed_streams,
        "product_streams_json": product_streams,
        "raw_summary_json": raw,
    }


def _parse_column_summary_text(text: str) -> dict | None:
    """text → COLUMN SUMMARY dict（内部供 parse_column_summary/parse_proii_out 共用）。"""
    lines = text.splitlines()
    # 找 COLUMN SUMMARY 段行范围（到下一个 SUMMARY 段或空行分隔）
    start_idx: int | None = None
    end_idx: int | None = None
    for i, line in enumerate(lines):
        if _COL_SUMMARY_HEADER in line.upper() and start_idx is None:
            start_idx = i + 1
            continue
        if start_idx is not None and end_idx is None:
            if line.strip() == "" or "SUMMARY" in line.upper() and "TRAY" not in line.upper():
                end_idx = i
                break
    if start_idx is None or end_idx is None:
        return None
    section = lines[start_idx:end_idx]

    result: dict = {
        "tower_uid": None,
        "tower_name": None,
        "num_stages": None,
        "condenser_type": None,
        "reboiler_type": None,
        "feed_stages_json": [],
        "product_streams_json": [],
        "tray_data_json": {},
        "compositions_json": {},
        "loading_json": {},
        "rating_json": {},
    }
    for line in section:
        if (m := _COL_NAME_RE.match(line)):
            result["tower_uid"] = m.group("uid")
            result["tower_name"] = m.group("name").strip()
        elif (m := _COL_STAGES_RE.match(line)):
            result["num_stages"] = int(m.group("n"))
        elif (m := _COL_CONDENSER_RE.match(line)):
            result["condenser_type"] = m.group("type").upper()
        elif (m := _COL_REBOILER_RE.match(line)):
            result["reboiler_type"] = m.group("type").upper()
        elif (m := _COL_FEED_RE.match(line)):
            result["feed_stages_json"].append(
                {"stream_id": m.group("sid"), "stage": int(m.group("stage"))}
            )
        elif (m := _COL_PRODUCT_RE.match(line)):
            result["product_streams_json"].append(m.group("sid"))

    # 后续段：TRAY COMPOSITIONS / LOADING
    post_section = lines[end_idx:]
    in_tray = False
    in_load = False
    current_stage: int | None = None
    for line in post_section:
        u = line.upper()
        if "TRAY COMPOSITIONS" in u:
            in_tray = True
            in_load = False
            current_stage = None
            continue
        if "TRAY LOADING" in u:
            in_tray = False
            in_load = True
            current_stage = None
            continue
        # 其他 SUMMARY 段 → 跳出
        if "SUMMARY" in u and "TRAY" not in u:
            in_tray = False
            in_load = False
            continue
        if in_tray:
            if (m := _TRAY_DATA_RE.match(line)):
                stage = int(m.group("stage"))
                current_stage = stage
                result["tray_data_json"].setdefault(stage, {})
                result["tray_data_json"][stage]["temp_k"] = float(m.group("t"))
                result["tray_data_json"][stage]["pressure_kpa"] = float(m.group("p"))
                continue
            if current_stage is not None and (m := _TRAY_COMP_RE.match(line)):
                result["compositions_json"].setdefault(current_stage, {})
                result["compositions_json"][current_stage][m.group("libid")] = float(
                    m.group("frac")
                )
        if in_load:
            if (m := _TRAY_LOAD_RE.match(line)):
                stage = int(m.group("stage"))
                result["loading_json"][stage] = {
                    "vapor_load": float(m.group("v")),
                    "liquid_load": float(m.group("l")),
                }
    return result


# ---------------------------------------------------------------------------
# P3.x SIM-19: 流 COMPOSITION 提取（spec §3.3.3）
# ---------------------------------------------------------------------------


def parse_compositions(inp_path: Path | str) -> dict[str, dict[str, float]]:
    """从 .inp 提取所有 PROPERTY STREAM 的 COMPOSITION(M/W)=N,f/N,f/...

    Args:
        inp_path: PRO/II .inp 文件路径

    Returns:
        dict: stream_tag → {component_alias: mole_or_mass_fraction, ...}
        - 无 COMPOSITION 段或无 STREAM → {}
        - 数值解析失败 → 跳过该 stream
    """
    inp_path = Path(inp_path)
    if not inp_path.exists():
        raise FileNotFoundError(f"PRO/II .inp not found: {inp_path}")
    text = inp_path.read_text(encoding="utf-8", errors="replace")

    # 1) 取 LIBID → alias 映射（libid 是整数）
    components = _parse_components(text)
    libid_to_alias: dict[int, str] = {}
    # components[0] 对应 LIBID=1, components[1] 对应 LIBID=2, ...
    for idx, comp_name in enumerate(components, start=1):
        libid_to_alias[idx] = map_libid_to_alias(comp_name)

    # 2) 取 STREAM DATA 段
    body = _join_continued_lines(text, "STREAM DATA", "UNIT OPERATIONS")
    if not body:
        return {}

    # 3) 行扫描（拼接 `&` 续行）
    joined_lines: list[str] = []
    buf = ""
    for line in body.splitlines():
        if line.rstrip().endswith("&"):
            buf += line.rstrip()[:-1] + " "
        else:
            buf += line
            joined_lines.append(buf)
            buf = ""
    if buf:
        joined_lines.append(buf)

    # 4) 解析每个 PROPERTY STREAM 行
    result: dict[str, dict[str, float]] = {}
    for jline in joined_lines:
        m = _STREAM_DEF_RE.search(jline)
        if not m:
            continue
        tag = m.group("tag")
        comp_match = _COMPOSITION_RE.search(jline)
        if not comp_match:
            continue
        comp_body = comp_match.group("body")
        fractions: dict[str, float] = {}
        for pair_m in _COMPOSITION_PAIR_RE.finditer(comp_body):
            try:
                libid = int(pair_m.group(1))
                frac = float(pair_m.group(2))
            except ValueError:
                continue
            alias = libid_to_alias.get(libid, f"LIBID_{libid}")
            fractions[alias] = frac
        if fractions:
            result[tag] = fractions
    return result


# ---------------------------------------------------------------------------
# 工具
# ---------------------------------------------------------------------------


def _join_continued_lines(text: str, section_start: str, section_end: str) -> str:
    """从 text 中截取 section_start 与 section_end 之间的文本块。

    不处理 `&` 续行（调用方负责）；仅做行范围裁剪。
    """
    lines = text.splitlines()
    start_idx: int | None = None
    end_idx: int | None = None
    for i, line in enumerate(lines):
        if start_idx is None and section_start.upper() in line.upper():
            start_idx = i + 1
            continue
        if start_idx is not None and section_end.upper() in line.upper():
            end_idx = i
            break
    if start_idx is None:
        return ""
    if end_idx is None:
        end_idx = len(lines)
    return "\n".join(lines[start_idx:end_idx])


# ===========================================================================
# P3.2 SIM-20: .out 20+ Section 数值提取（spec V1.6 §3.4.2）
# ===========================================================================
# 目标：单次 parse_proii_out_sections() 返回所有 section dict[section_name, payload]
# 性能预算：≤5s / 100 条（spec §3.4.2）
#
# 覆盖 section（与 PR-3~PR-10/PR-13 一致）：
# - banner / convergence_status / warnings
# - run_statistics（RUN STATISTICS 段，新增 SIM-20）
# - calculation_history（CALCULATION HISTORY 段，新增 SIM-20）
# - zero_flow / unreliable / reactions
# - unit_ops（PUMP/HX/MIXER/FLASH/VALVE/COMPRESSOR/SPLITTER/STCA/CALCULATOR）
# - column_summary（COLUMN SUMMARY）
# - stream_summary_rows（STREAM SUMMARY 原始行列表，未做 T/P 列拆分 — SIM-22+ 增强）
# - component_data（COMPONENT DATA 段，含 MW/DENSITY 等）
# - hcurve（HCURVE 段——本期未实现，返回 None）
# - reactor_summary / cstr_summary（PR-13/14——本期未实现，返回 None）
# ===========================================================================


def parse_proii_out_sections(out_path: Path | str) -> dict:
    """PRO/II .out 单文件一次性提取所有 section（spec §3.4.2 SIM-20 主入口）。

    Returns:
        dict: {
            "banner": str,
            "convergence_status": ConvergenceStatus,
            "warnings": list[str],
            "run_statistics": dict,         # NEW SIM-20
            "calculation_history": list[dict] | None,  # NEW SIM-20
            "zero_flow": list[str],
            "unreliable": list[str],
            "reactions": list[Reaction],
            "unit_ops": list[dict],
            "column_summary": dict | None,
            "stream_summary_rows": list[str],  # NEW SIM-20（原始行，未拆分列）
            "component_data": list[dict],     # NEW SIM-20（MW/DENSITY 等）
            "hcurve": None,                    # 待 P5 实现
            "reactor_summary": None,           # 待 SIM-15 扩展
            "cstr_summary": None,              # 待 SIM-15 扩展
        }

    Raises:
        FileNotFoundError: 文件不存在
        ValueError: .out 缺 banner（非 PRO/II 输出）
    """
    out_path = Path(out_path)
    if not out_path.exists():
        raise FileNotFoundError(f"PRO/II .out not found: {out_path}")
    text = out_path.read_text(encoding="utf-8", errors="replace")

    banner = _parse_banner(text)
    if banner is None:
        # 容错：缺标准 banner 但含 RUN STATISTICS/STREAM SUMMARY/COMPONENT DATA
        # 任一 PRO/II 特征段，仍视为合法 .out（banner 标 unknown）
        if not any(
            marker in text.upper()
            for marker in (
                "RUN STATISTICS",
                "STREAM SUMMARY",
                "COMPONENT DATA",
                "*** CONVERGENCE STATUS",
            )
        ):
            raise ValueError(f"PRO/II .out 缺 banner 行: {out_path}")
        banner = "unknown"

    # 收敛状态
    convergence = _parse_convergence_status(text)
    convergence, unit_status_map = _parse_unit_convergences(text, convergence)

    # warnings / reactions
    warnings = _parse_warnings(text)
    reactions = _parse_reactions(text)

    # zero_flow / unreliable 需要 streams（.inp 解析；本接口仅 .out，故容错返回空）
    # 注：完整 streams 需 .inp 配合——SIM-20 dispatcher 仅 .out，调用方可走 parse_proii_files
    zero_flow = _parse_zero_flow_streams(text, {})
    unreliable = _parse_unreliable_streams(warnings, unit_status_map, {})

    # unit_ops（已有 6 类 + PUMP/HX/MIXER/FLASH/VALVE/COLUMN）
    unit_ops = _parse_unit_op_summaries_text(text)

    # column summary
    column_summary = _parse_column_summary_text(text)

    # NEW SIM-20 sections
    run_stats = _parse_run_statistics(text)
    calc_history = _parse_calculation_history(text)
    stream_rows, properties_units, component_units = _parse_stream_summary_rows(text)
    comp_data = _parse_component_data(text)
    reactor_summary = _parse_reactor_summary(text)
    cstr_summary = _parse_cstr_summary(text)

    # SIM-20d：FCC 报告专属 REFINERY PROCESSOR + TBP/ASTM CURVES 段
    refinery_processor = _parse_refinery_processor(text)
    tbp_astm_curves = _parse_tbp_astm_curves(text)

    return {
        "banner": banner,
        "convergence_status": convergence,
        "warnings": warnings,
        "run_statistics": run_stats,
        "calculation_history": calc_history,
        "zero_flow": sorted(zero_flow),
        "unreliable": sorted(unreliable),
        "reactions": reactions,
        "unit_ops": unit_ops,
        "column_summary": column_summary,
        "streams": stream_rows,            # 列拆分后 list[dict]
        "stream_summary_rows": stream_rows,  # 别名（向后兼容）
        "properties_units": properties_units,  # SIM-20c：属性单位元数据
        "component_units": component_units,    # SIM-20c：组分表单位元数据
        "component_data": comp_data,
        "reactor_summary": reactor_summary,  # list[dict]
        "cstr_summary": cstr_summary,        # list[dict]
        # SIM-20d：FCC 报告专属段（化工 dmc.out 等无 REFINERY 段时为 []）
        "refinery_processor": refinery_processor,
        "tbp_astm": tbp_astm_curves,
        # HCURVE 在 PRO/II .out 中无 SUMMARY 段（仅 .inp 标识）→ 始终 None
        "hcurve": None,
    }


def _parse_run_statistics(text: str) -> dict:
    """RUN STATISTICS 段提取（spec §3.4.2）。

    字段：
        started: str | None（HH:MM:SS MM/DD/YY）
        finished: str | None
        errors: int | None（"NO ERRORS" → 0）
        warnings: int | None（"NO WARNINGS" → 0）
        messages: str | None
        interactive_seconds: float | None
        calculations_seconds: float | None
        total_seconds: float | None
    """
    out: dict = {
        "started": None,
        "finished": None,
        "errors": None,
        "warnings": None,
        "messages": None,
        "interactive_seconds": None,
        "calculations_seconds": None,
        "total_seconds": None,
    }
    lines = text.splitlines()
    in_section = False
    for line in lines:
        upper = line.upper().strip()
        if "*** RUN STATISTICS" in upper:
            in_section = True
            continue
        if in_section:
            # 段结束：下一个 *** 开头或 OVERALL
            if upper.startswith("***") or upper.startswith("OVERALL"):
                break
            # STARTED    21:07:27 03/04/98          NO ERRORS
            stripped = line.strip()
            if stripped.upper().startswith("STARTED"):
                parts = stripped.split()
                if len(parts) >= 3:
                    out["started"] = f"{parts[1]} {parts[2]}"
                if "NO ERRORS" in stripped.upper():
                    out["errors"] = 0
                else:
                    # 20 ERRORS
                    for i, p in enumerate(parts):
                        if p.upper() == "ERRORS" and i > 0:
                            try:
                                out["errors"] = int(parts[i - 1])
                            except ValueError:
                                pass
                if "NO WARNINGS" in stripped.upper():
                    out["warnings"] = 0
            elif stripped.upper().startswith("FINISHED"):
                parts = stripped.split()
                if len(parts) >= 3:
                    out["finished"] = f"{parts[1]} {parts[2]}"
                for i, p in enumerate(parts):
                    if p.upper() == "WARNINGS" and i > 0:
                        try:
                            out["warnings"] = int(parts[i - 1])
                        except ValueError:
                            pass
            elif "NO MESSAGES" in stripped.upper():
                out["messages"] = "NO MESSAGES"
            elif "MESSAGES" in stripped.upper():
                out["messages"] = stripped
            elif stripped.upper().startswith("INTERACTIVE"):
                out["interactive_seconds"] = _parse_min_sec(stripped)
            elif stripped.upper().startswith("CALCULATIONS"):
                out["calculations_seconds"] = _parse_min_sec(stripped)
            elif stripped.upper().startswith("TOTAL"):
                out["total_seconds"] = _parse_min_sec(stripped)
    return out


def _parse_min_sec(text: str) -> float | None:
    """'6 MIN, 39.97 SEC' → 6*60 + 39.97。"""
    import re
    m = re.search(r"(\d+)\s*MIN.*?([\d.]+)\s*SEC", text, re.IGNORECASE)
    if not m:
        return None
    return int(m.group(1)) * 60.0 + float(m.group(2))


def _parse_calculation_history(text: str) -> list[dict] | None:
    """CALCULATION HISTORY 段（spec §3.4.2）。

    段内每行格式典型：'INNER  0 : E(ENTH+SPEC) = 9.077E+01'
    返回 list[dict]，每条含 {label, value}。无段返回 None。
    """
    lines = text.splitlines()
    in_section = False
    rows: list[dict] = []
    for line in lines:
        upper = line.upper().strip()
        if "CALCULATION HISTORY" in upper:
            in_section = True
            continue
        if in_section:
            if upper.startswith("***") or upper.startswith("OVERALL"):
                break
            stripped = line.strip()
            if not stripped or stripped.startswith("-"):
                continue
            # 'INNER  0 : E(ENTH+SPEC) = 9.077E+01'
            if ":" in stripped:
                label, _, rest = stripped.partition(":")
                rows.append({"label": label.strip(), "value": rest.strip()})
    return rows if rows else None


def _parse_stream_summary_rows(text: str) -> tuple[list[dict], dict[str, str], dict[str, str]]:
    """PRO/II 物流解析主入口（用户 2026-09-10 完整版方案）。

    解析 4 类物流表：
      STREAM MOLAR COMPONENT PERCENTS — 组分摩尔百分数（mol%）
      STREAM WEIGHT COMPONENT RATES    — 组分质量流量（kg/hr）
      STREAM WEIGHT COMPONENT PERCENTS — 组分质量百分数（wt%）
      STREAM SUMMARY                   — 总流量 + 物性 + 子相（T/V/L）

    返回 tuple：(streams, properties_units, component_units)
      streams         list[dict]，每个 stream 一条
      properties_units dict[str, str] 属性名 → 单位（来自报告本身）
      component_units  dict[str, str] 三套基准固定单位（mol%/kg/hr/wt%）

    每个 stream 字段：
      stream_id / phase
      mol_percent / weight_rate / weight_percent 三个子 dict
      properties 子 dict（TEMPERATURE/PRESSURE/ENTHALPY/MW/MOLE FRAC 等）
      properties 字段同时拍平到顶层（temperature_c / pressure_kgcm2 / ...）

    单位元数据：每行属性名（如 'TEMPERATURE, C'）→ 属性名 + 单位；
    同属性多次出现时校验单位一致性（不一致仍采纳，不静默丢）。

    容错：
      跳过 TOC 数字行（'   233   STREAM SUMMARY'）
      跳过分隔行（= / -）
      N/A / 空 / **** 视为 None
      科学计数法（1.5042E-19）原样保留为 float
      FLUID MOLAR PERCENTS / FLUID WEIGHT RATES / FLUID WEIGHT PERCENTS 子段头
      切换 current_mode

    proii .out 纵表兼容：FEED/PROD 开头行也合并进 streams（type/name/from_tray
    等字段），与横表 stream 名冲突时按横表优先。
    """
    import re
    lines = text.splitlines()
    streams: dict[str, dict] = {}
    properties_units: dict[str, str] = {}
    current_ids: list[str] = []
    id_positions: list[int] = []
    needs_recalibration = False  # 进入新页后首个 RATE 行重写 id_positions
    current_mode: str | None = None  # 'mol' | 'rate' | 'wt' | None
    in_section = False
    vertical_rows: list[dict] = []  # 纵表回退（proii .out）
    toc_re = re.compile(r"^\s*\d+\s+STREAM\b", re.IGNORECASE)
    real_header_re = re.compile(
        r"^\s+STREAM\s+(SUMMARY|MOLAR|WEIGHT)\b",
        re.IGNORECASE,
    )
    stream_id_re = re.compile(r"^\s+STREAM ID\s+(.+)$", re.IGNORECASE)
    property_keywords = (
        "TOTAL RATE", "TEMPERATURE", "PRESSURE", "ENTHALPY",
        "MOLECULAR WEIGHT", "MOLE FRAC VAPOR", "MOLE FRAC LIQUID",
        "MOLE FRACTION VAPOR", "MOLE FRACTION LIQUID",
        "WEIGHT FRAC VAPOR", "WEIGHT FRAC LIQUID",
        "WEIGHT FRACTION VAPOR", "WEIGHT FRACTION LIQUID",
        "ACENTRIC FACTOR", "WATSON", "STD LIQ DENSITY", "SPECIFIC GRAVITY",
        "API GRAVITY", "SURFACE TENSION", "THERMAL COND", "VISCOSITY",
        "CP,", "CV,", "DENSITY", "COMPRESSIBILITY", "STD LIQ RATE",
        "REDUCED TEMP", "REDUCED PRES",
    )

    def get_or_init(sid: str) -> dict:
        if sid not in streams:
            streams[sid] = {
                "stream_id": sid,
                "phase": None,
                "name": None,
                "mol_percent": {},
                "weight_rate": {},
                "weight_percent": {},
                "properties": {},
            }
        return streams[sid]

    def parse_value_at(line: str, pos: int, end: int | None = None) -> float | None:
        slice_ = line[pos:end].strip()
        return _parse_numeric_or_none(slice_)

    def extract_values_by_positions(line: str) -> list[float | None]:
        """按 id_positions 切分每列的值（支持 N/A、空、****、科学计数法）。"""
        if not current_ids:
            return []
        result: list[float | None] = []
        for idx in range(len(current_ids)):
            start = id_positions[idx]
            end = (
                id_positions[idx + 1]
                if idx + 1 < len(id_positions)
                else len(line)
            )
            val = parse_value_at(line, start, end)
            result.append(val)
        return result

    def parse_property_line(line: str) -> None:
        """属性行（如 'TEMPERATURE, C  130.0  40.0  ...'）按列写入 properties。

        按 property_keywords 列表的优先级匹配行首。提取单位时只取紧跟逗号
        后的首个 token（避免误把整行数值当单位）。

        键归一化：用完整 label（含单位）走 _normalize_property_key，
        得到 'temperature_c' / 'pressure_kgcm2' 等。
        """
        stripped_left = line.lstrip()
        matched = None
        unit = ""
        full_label = ""
        for kw in property_keywords:
            if stripped_left.startswith(kw):
                matched = kw
                rest = stripped_left[len(kw):]
                if rest.startswith(","):
                    after_comma = rest[1:].lstrip()
                    parts_after = after_comma.split(None, 1)
                    if parts_after:
                        unit = parts_after[0]
                    full_label = f"{kw}, {unit}".rstrip(", ")
                else:
                    full_label = kw
                break
        if not matched:
            return
        properties_units[matched] = unit
        # 按列位置取值
        result: list[float | None] = []
        for idx in range(len(current_ids)):
            start = id_positions[idx]
            end = (
                id_positions[idx + 1]
                if idx + 1 < len(id_positions)
                else len(line)
            )
            slice_ = line[start:end].strip() if start < len(line) else ""
            val = _parse_numeric_or_none(slice_)
            result.append(val)
        # 用 _normalize_property_key 归一化键（含单位后缀）
        norm_key = _normalize_property_key(full_label)
        for sid, val in zip(current_ids, result, strict=False):
            if val is not None:
                get_or_init(sid)["properties"][norm_key] = val

    def parse_component_line(line: str) -> None:
        """组分数据行：'    1  H2O          0.0361   9.1951E-14   ...'"""
        m = re.match(r"^\s*(\d+)\s+([A-Za-z0-9]+)\s+(.*)$", line)
        if not m or current_mode not in ("mol", "rate", "wt"):
            return
        comp_name = m.group(2)
        values = extract_values_by_positions(line)
        for sid, val in zip(current_ids, values, strict=False):
            target = get_or_init(sid)
            if val is None:
                continue
            if current_mode == "mol":
                target["mol_percent"][comp_name] = val
            elif current_mode == "rate":
                target["weight_rate"][comp_name] = val
            elif current_mode == "wt":
                target["weight_percent"][comp_name] = val

    for line in lines:
        upper = line.upper().strip()
        if not in_section:
            if toc_re.match(line):
                continue
            if real_header_re.match(line):
                in_section = True
                current_mode = None
                continue
            continue
        # in_section 之后：
        if line.strip().startswith("***"):
            in_section = False
            current_ids = []
            id_positions = []
            needs_recalibration = False
            current_mode = None
            continue
        # 页分隔（PRO/II 用 ^L form feed）→ 复位 current_ids 让下一个
        # STREAM ID 行重新建立，但保持 in_section=True
        if "\f" in line:
            current_ids = []
            id_positions = []
            needs_recalibration = False
            current_mode = None
            continue
        if upper.startswith("OVERALL") or upper.startswith("END OF RUN"):
            in_section = False
            current_ids = []
            id_positions = []
            needs_recalibration = False
            current_mode = None
            continue
        # STREAM ID 行：建立当前页 stream 列表 + 列位置（待 RATE 行校准）
        m = stream_id_re.match(line)
        if m:
            after = m.group(1)
            ids = re.findall(r"\S+", after)
            if ids:
                current_ids = ids
                positions = [line.find(sid) for sid in ids]
                sorted_pairs = sorted(zip(positions, ids, strict=True))
                id_positions = [p for p, _ in sorted_pairs]
                current_ids = [sid for _, sid in sorted_pairs]
                needs_recalibration = True
            continue
        # RATE/TOTAL RATE/STD LIQ RATE 等典型数值行：用以重新校准列起点
        # PRO/II STREAM ID 位置与数据列起点不严格对齐（ID 在列内左侧），
        # 但 RATE 等数值行右对齐到列末尾。用首个数值行作为列位置的真值。
        if (
            needs_recalibration
            and current_ids
            and re.match(r"^\s+(RATE|TOTAL RATE|STD LIQ RATE),", line)
        ):
            positions_found = [
                m.start()
                for m in re.finditer(r"-?\d+\.\d+(?:E[+-]?\d+)?", line)
            ]
            if len(positions_found) == len(current_ids):
                id_positions = positions_found
                needs_recalibration = False
            # 不 continue → 让 parse_property_line 也处理（写 properties + units）
        if upper.startswith("NAME"):
            continue
        if upper.startswith("PHASE"):
            parts = upper.split()[1:]
            for sid, p in zip(current_ids, parts, strict=False):
                if p in {"LIQUID", "VAPOR", "MIXED", "VAP/LIQ", "SOLID"}:
                    get_or_init(sid)["phase"] = p
            continue
        if "FLUID MOLAR PERCENTS" in upper:
            current_mode = "mol"
            continue
        if "FLUID MOLAR RATES" in upper or "FLUID RATES" in upper:
            current_mode = "rate"
            continue
        if "FLUID WEIGHT RATES" in upper:
            current_mode = "rate"
            continue
        if "FLUID WEIGHT PERCENTS" in upper:
            current_mode = "wt"
            continue
        # 纵表兼容：proii .out 的 FEED/PROD 开头行
        if not current_ids and upper.startswith(("FEED", "PROD", "RECYCLE")):
            vertical_rows.append(_split_stream_row(line))
            continue
        if not current_ids:
            continue
        # 组分数据行（数字 + 名称开头）
        if re.match(r"^\s*\d+\s+\S+", line):
            parse_component_line(line)
            continue
        # 属性行
        parse_property_line(line)

    # 合并纵表行（proii .out 兼容）：按 name 加入
    for vrow in vertical_rows:
        name = vrow.get("name")
        if not name:
            continue
        target = get_or_init(name)
        # name/stream_id 允许覆盖 None（横表创建时可能为 None）
        if not target.get("name"):
            target["name"] = name
        if not target.get("stream_id"):
            target["stream_id"] = name
        for k, v in vrow.items():
            if v is None:
                continue
            if k in {"type", "from_tray", "to_tray", "liquid_frac",
                      "flow_kmolph", "heat_mkcalph", "phase"}:
                target.setdefault(k, v)

    # "FEED AND PRODUCT STREAMS" 段纵表（column summary 段内，含
    # TYPE/STREAM/PHASE/FROM/TO/LIQUID FRAC/FLOW RATES/HEAT RATES 列）
    feed_prod_re = re.compile(r"^\s+FEED AND PRODUCT STREAMS\s*$", re.IGNORECASE)
    fp_in = False
    fp_dashes_seen = False
    fp_column_starts: list[int] = []
    fp_header_line: str = ""
    fp_dashes_line: str = ""
    for line in lines:
        if feed_prod_re.match(line):
            fp_in = True
            fp_dashes_seen = False
            fp_column_starts = []
            fp_header_line = ""
            fp_dashes_line = ""
            continue
        if fp_in:
            stripped = line.strip()
            if not stripped:
                continue
            if stripped.startswith("***"):
                fp_in = False
                continue
            # dashes row (-----)：与 header 一起解析列起点
            if stripped.startswith("---"):
                fp_dashes_seen = True
                fp_dashes_line = line
                fp_column_starts = _detect_column_starts(fp_header_line, fp_dashes_line)
                continue
            # 检测表头第一行："  TYPE     STREAM    PHASE   FROM  TO   LIQUID ..."
            if (
                not fp_dashes_seen
                and "TYPE" in line
                and "STREAM" in line
                and "PHASE" in line
            ):
                fp_header_line = line
                continue
            # 段尾（下一个 OVERALL 或 SPECIFICATIONS）
            if stripped.startswith("OVERALL") or stripped.startswith("PSEUDO") \
                    or stripped.startswith("SPECIFICATIONS") \
                    or stripped.startswith("PARAMETER"):
                fp_in = False
                continue
            # 纵表行：FEED/PROD/RECYCLE/NET 开头
            if re.match(r"^\s*(FEED|PROD|RECYCLE|NET)\s+\S+", line):
                row = _split_stream_row(line, fp_column_starts)
                name = row.get("name")
                if name:
                    target = get_or_init(name)
                    if not target.get("name"):
                        target["name"] = name
                    if not target.get("stream_id"):
                        target["stream_id"] = name
                    for k, v in row.items():
                        if v is None:
                            continue
                        if k in {"type", "from_tray", "to_tray",
                                  "liquid_frac", "flow_kmolph",
                                  "heat_mkcalph", "phase"}:
                            target.setdefault(k, v)

    # 把 properties 字段拍平到顶层（兼容 SIM-22 PropertyConflictResolver 调用）
    result: list[dict] = []
    for _sid, s in streams.items():
        flat = {**s}
        props = s.get("properties") or {}
        for prop_name, val in props.items():
            flat[prop_name] = val
        result.append(flat)

    # 固定单位元数据（组分表）
    component_units = {
        "mol_percent": "mol%",
        "weight_rate": "kg/hr",
        "weight_percent": "wt%",
    }
    return result, properties_units, component_units


def _normalize_property_key(label: str) -> str:
    """PRO/II 物性行标签 → 统一 snake_case 字段名。

    例：
        'TEMPERATURE, C'           → 'temperature_c'
        'PRESSURE, KG/CM2'         → 'pressure_kgcm2'
        'MOLECULAR WEIGHT'         → 'molecular_weight'
        'RATE, KG-MOL/HR'          → 'rate_kgmolph'
        'ENTHALPY, M*KCAL/HR'      → 'enthalpy_mkcalph'
        'ENTHALPY, KCAL/KG'        → 'enthalpy_kcal_kg'
        'STD LIQ DENSITY, KG/M3'   → 'std_liq_density_kgm3'
        'SPECIFIC GRAVITY (AIR=1.0)' → 'specific_gravity_air'
        'REDUCED TEMP (KAYS RULE)' → 'reduced_temp_kays'
    """
    s = label.strip().upper()
    # 去掉括号注释
    s = re.sub(r"\s*\([^)]*\)\s*", " ", s).strip()
    # 单位映射
    unit_map = {
        "C": "c",
        "KG/CM2": "kgcm2",
        "KG-MOL/HR": "kgmolph",
        "M*KCAL/HR": "mkcalph",
        "KCAL/KG": "kcal_kg",
        "KCAL/KG-C": "kcal_kg_c",
        "KG/M3": "kgm3",
        "KG/HR": "kgph",
        "M3/HR": "m3ph",
        "K*M3/HR": "km3ph",
        "CP": "cp",
        "PSI": "psi",
    }
    # 拆 "TEMPERATURE, C" → ('TEMPERATURE', 'C')
    parts = [p.strip() for p in s.split(",")]
    name = parts[0]
    unit = parts[1] if len(parts) > 1 else ""
    name_snake = re.sub(r"\s+", "_", name.lower())
    if unit:
        unit_norm = unit_map.get(unit.strip(), unit.lower().replace("/", "_"))
        return f"{name_snake}_{unit_norm}"
    return name_snake


def _parse_numeric_or_none(token: str) -> float | None:
    """N/A / 空 / 非数字 → None；否则 float。"""
    s = token.strip()
    if not s or s.upper() in {"N/A", "NA", "-", "****", "*"}:
        return None
    try:
        return float(s)
    except ValueError:
        return None


def _detect_column_starts(header_line: str, dashes_line: str) -> list[int]:
    """从 FEED AND PRODUCT STREAMS 表头+dashes 行识别 8 列起点。

    header_line: '  TYPE     STREAM    PHASE   FROM  TO   LIQUID ...'
    dashes_line: '  ----- ------------ ------  ---- ----  ------ ...'

    数据列起点 = dashes 段左端位置。返回 8 个整数（TYPE/STREAM/PHASE/
    FROM TRAY/TO TRAY/LIQUID FRAC/FLOW RATES/HEAT RATES 起点）。如果
    dashes 段数 ≠ 8 退化为从 header 提取。
    """
    # 主路径：dashes 行每段 '-' 起点 = 列起点
    groups: list[tuple[int, int]] = []
    i = 0
    n = len(dashes_line)
    while i < n:
        if dashes_line[i] == "-":
            j = i
            while j < n and dashes_line[j] == "-":
                j += 1
            groups.append((i, j))
            i = j
        else:
            i += 1
    if len(groups) == 8:
        return [g[0] for g in groups]
    # 回退：从 header 提取
    keywords = ["TYPE", "STREAM", "PHASE", "FROM", "TO", "LIQUID",
                "FLOW RATES", "HEAT RATES"]
    starts: list[int] = []
    for kw in keywords:
        pos = header_line.find(kw)
        if pos < 0:
            return []
        starts.append(pos)
    if len(starts) >= 7 and starts[6] < starts[5]:
        return []
    return starts


def _split_stream_row(line: str, column_starts: list[int] | None = None) -> dict:
    """单条 STREAM SUMMARY 数据行列拆分（PRO/II FEED AND PRODUCT STREAMS 段）。

    典型行格式（PRO/II 8 列固定列宽表头）：
        FEED  A            MIXED          25   .8091             120.35        2.9552
        PROD  D            LIQUID     1                           18.68         .2768
        PROD  E            LIQUID    45                          101.67        2.5285

    关键：FROM TRAY 列允许空白（空白 → None），不能用 split() 按位置。
    用 column_starts（来自表头行）切分字段，对空白段返回 None。
    column_starts 为空时退回到经验默认偏移（可能与实际不符）。
    """
    out: dict = {
        "type": None,
        "name": None,
        "phase": None,
        "from_tray": None,
        "to_tray": None,
        "liquid_frac": None,
        "flow_kmolph": None,
        "heat_mkcalph": None,
    }
    if len(line) < 7:
        return out

    if not column_starts:
        # 回退：经验默认偏移（只对 line 466-468 风格有效）
        column_starts = [2, 7, 19, 26, 33, 38, 46, 58]

    def slice_field(start: int, end: int) -> str:
        s = line[start:end] if end <= len(line) else line[start:]
        return s.strip()

    def parse_num(s: str, as_int: bool) -> int | float | None:
        if not s:
            return None
        try:
            return int(s) if as_int else float(s)
        except (ValueError, TypeError):
            return None

    # column_starts 8 个值：TYPE/STREAM/PHASE/FROM/TO/LIQ_FRAC/FLOW/HEAT
    type_end = column_starts[1] if len(column_starts) > 1 else len(line)
    name_end = column_starts[2] if len(column_starts) > 2 else len(line)
    phase_end = column_starts[3] if len(column_starts) > 3 else len(line)
    from_end = column_starts[4] if len(column_starts) > 4 else len(line)
    to_end = column_starts[5] if len(column_starts) > 5 else len(line)
    liq_end = column_starts[6] if len(column_starts) > 6 else len(line)
    heat_end = column_starts[7] if len(column_starts) > 7 else len(line)

    out["type"] = slice_field(column_starts[0], type_end).upper() or None
    out["name"] = slice_field(column_starts[1], name_end) or None

    phase_str = slice_field(column_starts[2], phase_end).upper()
    if phase_str in {"MIXED", "LIQUID", "VAPOR", "VAP/LIQ", "SOLID"}:
        out["phase"] = phase_str

    out["from_tray"] = parse_num(
        slice_field(column_starts[3], from_end), as_int=True)
    out["to_tray"] = parse_num(
        slice_field(column_starts[4], to_end), as_int=True)
    out["liquid_frac"] = parse_num(
        slice_field(column_starts[5], liq_end), as_int=False)
    out["flow_kmolph"] = parse_num(
        slice_field(column_starts[6], heat_end), as_int=False)
    out["heat_mkcalph"] = parse_num(
        slice_field(column_starts[7], len(line)), as_int=False)

    return out


def _parse_reactor_summary(text: str) -> list[dict]:
    """REACTOR SUMMARY 段（spec §3.4.2 PR-13）。

    每段典型结构（sample 行 7885+）：
        REACTOR SUMMARY  02/09/99
        UNIT 11, 'R101'
        REACTOR TYPE   ADIABATIC REACTOR
        DUTY, M*KCAL/HR   -2.57361E-08
        FEED         S5
        LIQUID PRODUCT  S4
        TEMPERATURE, C  127.24  169.94
        PRESSURE, KG/CM2  36.7  36.2

    提取 list[dict]，每条 reactor 一条记录：
        unit_id / reactor_type / duty_mkcalph /
        heat_of_reaction_mkcalph /
        feed_stream / liquid_product / temperature_in_c /
        temperature_out_c / pressure_in_kgcm2 / pressure_out_kgcm2
    """
    import re
    lines = text.splitlines()
    rows: list[dict] = []
    header_re = re.compile(r"^\s+REACTOR SUMMARY\b", re.IGNORECASE)
    unit_re = re.compile(r"^\s*UNIT\s+\d+,\s*'([^']+)'", re.IGNORECASE)
    type_re = re.compile(r"^\s*REACTOR TYPE\s+(.+)$", re.IGNORECASE)
    duty_re = re.compile(r"^\s*DUTY,\s*M\*KCAL/HR\s+([\d.E+\-]+)\s*$",
                         re.IGNORECASE)
    hor_re = re.compile(
        r"^\s*TOTAL HEAT OF REACTION AT [\d.]+\s*C,\s*M\*KCAL/HR\s+"
        r"([\d.E+\-]+)\s*$", re.IGNORECASE
    )
    feed_re = re.compile(r"^\s*FEED\s+(\S+)\s*$", re.IGNORECASE)
    prod_re = re.compile(r"^\s*LIQUID PRODUCT\s+(\S+)\s*$", re.IGNORECASE)
    temp_re = re.compile(
        r"^\s*TEMPERATURE,\s*C\s+([\d.E+\-]+)\s+([\d.E+\-]+)\s*$",
        re.IGNORECASE
    )
    pres_re = re.compile(
        r"^\s*PRESSURE,\s*KG/CM2\s+([\d.E+\-]+)\s+([\d.E+\-]+)\s*$",
        re.IGNORECASE
    )
    in_section = False
    current: dict | None = None
    for line in lines:
        upper = line.upper().strip()
        if not in_section:
            if header_re.match(line):
                in_section = True
                continue
            continue
        # 段结束：下一段 banner（*** 开头或新 SUMMARY）
        if line.strip().startswith("***"):
            if current is not None:
                rows.append(current)
                current = None
            break
        if re.match(r"^\s+(COLUMN|STREAM|PUMP|MIXER|HX|FLASH)\s+SUMMARY\b",
                    upper):
            if current is not None:
                rows.append(current)
                current = None
            in_section = False
            continue
        m = unit_re.match(line)
        if m:
            if current is not None:
                rows.append(current)
            current = {"unit_id": m.group(1)}
            continue
        if current is None:
            continue
        m = type_re.match(line)
        if m:
            current["reactor_type"] = m.group(1).strip()
            continue
        m = duty_re.match(line)
        if m:
            try:
                current["duty_mkcalph"] = float(m.group(1))
            except ValueError:
                pass
            continue
        m = hor_re.match(line)
        if m:
            try:
                current["heat_of_reaction_mkcalph"] = float(m.group(1))
            except ValueError:
                pass
            continue
        m = feed_re.match(line)
        if m and "feed_stream" not in current:
            current["feed_stream"] = m.group(1)
            continue
        m = prod_re.match(line)
        if m and "liquid_product" not in current:
            current["liquid_product"] = m.group(1)
            continue
        m = temp_re.match(line)
        if m:
            try:
                current["temperature_in_c"] = float(m.group(1))
                current["temperature_out_c"] = float(m.group(2))
            except ValueError:
                pass
            continue
        m = pres_re.match(line)
        if m:
            try:
                current["pressure_in_kgcm2"] = float(m.group(1))
                current["pressure_out_kgcm2"] = float(m.group(2))
            except ValueError:
                pass
            continue
    if current is not None:
        rows.append(current)
    return rows


def _parse_cstr_summary(text: str) -> list[dict]:
    """CSTR SUMMARY 段（spec §3.4.2 PR-14）。

    结构同 REACTOR SUMMARY（sample 行 8038+），额外含 CSTR 特有：
        VOLUME, M3 / SPACE-TIME, HR / SPACE-VELOCITY, /HR

    字段同 REACTOR + volume_m3 / space_time_hr / space_velocity_per_hr。
    """
    import re
    lines = text.splitlines()
    rows: list[dict] = []
    header_re = re.compile(r"^\s+CSTR SUMMARY\b", re.IGNORECASE)
    unit_re = re.compile(r"^\s*UNIT\s+\d+,\s*'([^']+)'", re.IGNORECASE)
    type_re = re.compile(r"^\s*REACTOR TYPE\s+(.+)$", re.IGNORECASE)
    duty_re = re.compile(r"^\s*DUTY,\s*M\*KCAL/HR\s+([\d.E+\-]+)\s*$",
                         re.IGNORECASE)
    hor_re = re.compile(
        r"^\s*TOTAL HEAT OF REACTION AT [\d.]+\s*C,\s*M\*KCAL/HR\s+"
        r"([\d.E+\-]+)\s*$", re.IGNORECASE
    )
    volume_re = re.compile(r"^\s*VOLUME,\s*M3\s+([\d.E+\-]+)\s*$",
                           re.IGNORECASE)
    st_re = re.compile(
        r"^\s*SPACE-TIME,\s*HR\s+AT OUTLET CONDITIONS\s+([\d.E+\-]+)\s*$",
        re.IGNORECASE
    )
    sv_re = re.compile(
        r"^\s*SPACE-VELOCITY,\s*/HR\s+AT OUTLET CONDITIONS\s+"
        r"([\d.E+\-]+)\s*$", re.IGNORECASE
    )
    feed_re = re.compile(r"^\s*FEED\s+(\S+)\s*$", re.IGNORECASE)
    prod_re = re.compile(r"^\s*LIQUID PRODUCT\s+(\S+)\s*$", re.IGNORECASE)
    temp_re = re.compile(
        r"^\s*TEMPERATURE,\s*C\s+([\d.E+\-]+)\s+([\d.E+\-]+)\s*$",
        re.IGNORECASE
    )
    pres_re = re.compile(
        r"^\s*PRESSURE,\s*KG/CM2\s+([\d.E+\-]+)\s+([\d.E+\-]+)\s*$",
        re.IGNORECASE
    )
    in_section = False
    current: dict | None = None
    for line in lines:
        upper = line.upper().strip()
        if not in_section:
            if header_re.match(line):
                in_section = True
                continue
            continue
        if line.strip().startswith("***"):
            if current is not None:
                rows.append(current)
                current = None
            break
        if re.match(r"^\s+(COLUMN|STREAM|PUMP|MIXER|HX|FLASH|REACTOR)\s+"
                    r"SUMMARY\b", upper):
            if current is not None:
                rows.append(current)
                current = None
            in_section = False
            continue
        m = unit_re.match(line)
        if m:
            if current is not None:
                rows.append(current)
            current = {"unit_id": m.group(1)}
            continue
        if current is None:
            continue
        m = type_re.match(line)
        if m:
            current["reactor_type"] = m.group(1).strip()
            continue
        m = duty_re.match(line)
        if m:
            try:
                current["duty_mkcalph"] = float(m.group(1))
            except ValueError:
                pass
            continue
        m = hor_re.match(line)
        if m:
            try:
                current["heat_of_reaction_mkcalph"] = float(m.group(1))
            except ValueError:
                pass
            continue
        m = volume_re.match(line)
        if m:
            try:
                current["volume_m3"] = float(m.group(1))
            except ValueError:
                pass
            continue
        m = st_re.match(line)
        if m:
            try:
                current["space_time_hr"] = float(m.group(1))
            except ValueError:
                pass
            continue
        m = sv_re.match(line)
        if m:
            try:
                current["space_velocity_per_hr"] = float(m.group(1))
            except ValueError:
                pass
            continue
        m = feed_re.match(line)
        if m and "feed_stream" not in current:
            current["feed_stream"] = m.group(1)
            continue
        m = prod_re.match(line)
        if m and "liquid_product" not in current:
            current["liquid_product"] = m.group(1)
            continue
        m = temp_re.match(line)
        if m:
            try:
                current["temperature_in_c"] = float(m.group(1))
                current["temperature_out_c"] = float(m.group(2))
            except ValueError:
                pass
            continue
        m = pres_re.match(line)
        if m:
            try:
                current["pressure_in_kgcm2"] = float(m.group(1))
                current["pressure_out_kgcm2"] = float(m.group(2))
            except ValueError:
                pass
            continue
    if current is not None:
        rows.append(current)
    return rows


def _parse_component_data(text: str) -> list[dict]:
    """COMPONENT DATA 段（spec §3.4.2）。

    表格行典型：'  1  H2O          LIBRARY  VAP/LIQ  18.015  998.566'
    提取 {index, name, type, phase, mw, density}。
    """
    import re
    lines = text.splitlines()
    rows: list[dict] = []
    in_section = False
    for line in lines:
        upper = line.upper().strip()
        if "COMPONENT DATA" in upper:
            in_section = True
            continue
        if in_section:
            if upper.startswith("***") and "COMPONENT DATA" not in upper:
                break
            if "STREAM SUMMARY" in upper or "OVERALL" in upper:
                break
            stripped = line.rstrip()
            if not stripped or set(stripped) <= {"-", "="}:
                continue
            # 匹配：<num> <name> <comp_type> <phase> <mw> <density?>
            m = re.match(
                r"\s*(\d+)\s+(\S+)\s+(LIBRARY|PETRO\s*CUT)\s+"
                r"(VAP/LIQ|VAPOR|LIQUID|SOLID|MIXED)\s+"
                r"([\d.]+)\s*([\d.]+)?",
                stripped,
            )
            if m:
                rows.append({
                    "index": int(m.group(1)),
                    "name": m.group(2),
                    "type": m.group(3).replace(" ", ""),
                    "phase": m.group(4),
                    "mw": float(m.group(5)),
                    "density": float(m.group(6)) if m.group(6) else None,
                })
    return rows


# ---------------------------------------------------------------------------
# SIM-20d: REFINERY PROCESSOR PROPERTIES SET + TBP/ASTM CURVES（FCC 报告专属）
# ---------------------------------------------------------------------------

# REFINERY + TBP/ASTM 子段头（小写 → 子段名）
# 形如 '--- TOTAL STREAM - WET BASIS (INCLUDES ANY FREE AND DISSOLVED WATER) ---'
# 提取 'total_wet' / 'vapor_wet' / 'liquid_wet' / 'total_dry' / ...
_REFINERY_SUBSECTION_RE = re.compile(
    r"^\s*-{3,}\s*(TOTAL STREAM|VAPOR PHASE|LIQUID PHASE)"
    r"\s*-\s*(WET|DRY)\s+BASIS\b.*-{3,}\s*$",
    re.IGNORECASE,
)
_REFINERY_HEADER_RE = re.compile(
    r"^\s*REFINERY PROCESSOR PROPERTIES SET\b", re.IGNORECASE,
)
_TBPASTM_HEADER_RE = re.compile(
    r"^\s*STREAM TBP/ASTM CURVES\b", re.IGNORECASE,
)
_TBPASTM_CURVE_RE = re.compile(
    r"^\s*(TBP|ASTM\s+D\d+)\b(.*)$", re.IGNORECASE,
)


def _detect_section_label(raw_header: str) -> str:
    """REFINERY 子段头 → 'total_wet' / 'vapor_wet' / 'liquid_dry' 形式。"""
    upper = raw_header.upper()
    phase_part = "total"
    if "VAPOR PHASE" in upper:
        phase_part = "vapor"
    elif "LIQUID PHASE" in upper:
        phase_part = "liquid"
    basis_part = "wet"
    if "DRY" in upper and "WET" not in upper:
        basis_part = "dry"
    elif "WET" in upper:
        basis_part = "wet"
    return f"{phase_part}_{basis_part}"


def _detect_phase_column_starts(line: str, num_streams: int) -> list[int]:
    """PHASE / THERMO ID 行按 token cluster 识别列起点。

    PRO/II PHASE 行每个 stream 是一段连续 token（可能 1 个如 'VAPOR'，
    也可能 2 个如 'DRY LIQUID' 或 'WATER VAPOR'）。列内 token 之间只
    隔 1 个空格；列间至少 2 个连续空格。
    策略：扫所有 token，找到 num_streams 个列起点（每列第一个 token 起点）。
    """
    # 跳过 'PHASE' / 'THERMO ID' 前缀
    keyword_m = re.match(
        r"^\s*(PHASE|THERMO\s+ID)\s+", line, re.IGNORECASE,
    )
    if not keyword_m:
        return []
    search_start = keyword_m.end()
    # 扫描 token + 间隙
    n = len(line)
    tokens: list[tuple[int, int]] = []  # (start, end)
    i = search_start
    while i < n:
        while i < n and line[i].isspace():
            i += 1
        if i >= n:
            break
        tok_start = i
        while i < n and not line[i].isspace():
            i += 1
        tokens.append((tok_start, i))
    if not tokens:
        return []
    # 每个 stream 占连续 token 数。简化：每列 token 数 = round(total/num_streams)
    # 但 PHASE 列内 token 数可能不同（DRY LIQUID 是 2，VAPOR 是 1）。
    # 真实 PRO/II 输出每列 token 数固定（实测 2: 'DRY LIQUID' / 'WATER VAPOR'）。
    # 用 first stream 的 token 数作为基准。
    # 简单策略：先把所有 token 分成 num_streams 个等大组；
    # 如 PHASE 行是 'DRY LIQUID  WATER VAPOR  WATER VAPOR  WATER VAPOR'（8 tokens），
    # num_streams=4 → 每组 2 token。
    n_tokens = len(tokens)
    tokens_per_stream = max(1, n_tokens // num_streams)
    starts: list[int] = []
    for i in range(num_streams):
        idx = i * tokens_per_stream
        if idx < n_tokens:
            starts.append(tokens[idx][0])
        else:
            starts.append(tokens[-1][0])
    return starts


def _split_phase_row_by_columns(line: str, column_starts: list[int]) -> list[str]:
    """PHASE / THERMO ID 行按 column_starts 切出每列文本。

    与数据行不同，PHASE 是文本（非数值），不能 re.finditer。
    按 column_starts 切片后 strip，对每列保留原文（去多余空白后大写）。
    每列 slice 终点是下一列的起点（或行尾），允许跨多个空白 token。
    """
    if not column_starts:
        return []
    bounds = list(column_starts) + [len(line)]
    result: list[str] = []
    for idx in range(len(column_starts)):
        start = bounds[idx]
        end = bounds[idx + 1]
        chunk = line[start:end].strip().upper()
        # 移除多余的内部空白（'DRY  LIQUID' → 'DRY LIQUID'）
        chunk = " ".join(chunk.split())
        result.append(chunk)
    return result


def _split_thermo_row_by_columns(line: str, column_starts: list[int]) -> list[str]:
    """THERMO ID 行按列切（每列 1 个 ID 如 'SRK' / 'BK10'）。"""
    return _split_phase_row_by_columns(line, column_starts)


def _parse_refinery_processor(text: str) -> list[dict]:
    """REFINERY PROCESSOR PROPERTIES SET 段解析（FCC 报告专属，SIM-20d）。

    每条 stream dict：
        stream_id      str
        phase          str（DRY LIQUID/WET VAPOR/DRY VAPOR/WET LIQUID 等）
        thermo_id      str | None
        properties     dict[str, dict[str, float | None]]
                        按子段名（total_wet/vapor_wet/liquid_wet/total_dry/...）
                        二级嵌套；每子段内 key 为 snake_case 物性名（如
                        'temperature_c' / 'pressure_mpa' / 'rate_kgmolph'）。

    跨页同 stream 名按 stream_id 合并（first non-None wins）。
    跨页同 stream 不同 phase/thermo_id 仍以第一个为权威（PRO/II 报告风格）。

    Returns:
        list[dict]；空 list 表示 .out 不含 REFINERY 段。
    """
    lines = text.splitlines()
    streams: dict[str, dict] = {}
    in_refinery = False
    current_ids: list[str] = []
    current_phase: list[str | None] = []
    current_thermo: list[str | None] = []
    id_positions: list[int] = []
    current_subsection: str | None = None

    def get_or_init(sid: str) -> dict:
        if sid not in streams:
            streams[sid] = {
                "stream_id": sid,
                "phase": None,
                "thermo_id": None,
                "properties": {},
            }
        return streams[sid]

    def reset_page_state() -> None:
        nonlocal current_ids, current_phase, current_thermo
        nonlocal id_positions, current_subsection
        current_ids = []
        current_phase = []
        current_thermo = []
        id_positions = []
        current_subsection = None

    stream_id_re = re.compile(r"^\s+STREAM ID\s+(.+)$", re.IGNORECASE)
    name_re = re.compile(r"^\s+NAME\b", re.IGNORECASE)
    phase_re = re.compile(r"^\s+PHASE\b", re.IGNORECASE)
    thermo_re = re.compile(r"^\s+THERMO ID\b", re.IGNORECASE)
    # 数值行：行首一个或多个空白 + (RATE|TEMPERATURE|PRESSURE|ENTHALPY|MW|...)
    # 以全大写开头，后跟逗号+单位（可无）。识别后按列位置提取每个 stream 的值。
    refinery_property_keywords = (
        "TEMPERATURE", "PRESSURE", "RATE", "ENTHALPY",
        "MOLECULAR WEIGHT", "WATSON", "FLASH POINT", "RVP", "TVP",
        "ACT RATE", "ACT DENS", "ACT DENSITY", "NORM VAP RATE",
        "STD LV RATE", "STD SP.GR.", "STD SP.GR",
        "CP,", "CV,", "DENSITY", "COMPRESSIBILITY",
        "VISCOSITY", "STD LIQ DENSITY",
    )

    needs_recalibration = False  # 进入新页后首个数值行重写 id_positions

    def extract_values(line: str) -> list[float | None]:
        if not current_ids:
            return []
        out: list[float | None] = []
        for idx in range(len(current_ids)):
            start = id_positions[idx]
            end = (
                id_positions[idx + 1]
                if idx + 1 < len(id_positions)
                else len(line)
            )
            slice_ = line[start:end].strip() if start < len(line) else ""
            out.append(_parse_numeric_or_none(slice_))
        return out

    def parse_refinery_property_line(line: str) -> None:
        stripped_left = line.lstrip()
        matched_kw = None
        unit = ""
        full_label = ""
        for kw in refinery_property_keywords:
            if stripped_left.startswith(kw):
                matched_kw = kw
                rest = stripped_left[len(kw):]
                if rest.startswith(","):
                    after_comma = rest[1:].lstrip()
                    parts_after = after_comma.split(None, 1)
                    if parts_after:
                        unit = parts_after[0]
                    full_label = f"{kw}, {unit}".rstrip(", ")
                else:
                    full_label = kw
                break
        if not matched_kw or current_subsection is None:
            return
        # REFINERY：每个属性行独立检测数值位置（不同属性值宽度不同——如
        # RATE 第一列 1.9119E-07 比 TEMPERATURE 第一列 250.00 宽）。按行
        # 内实际数值起点→下一数值起点切片，避免 STREAM ID 位置/RATE 位置
        # 与 TEMPERATURE 位置错位（实测 FCC 报告 STREAM ID 列与数据列起点
        # 不一致：FO1 在 37 而 250.00 在 34）。
        if not current_ids:
            return
        value_positions = [
            mm.start() for mm in re.finditer(
                r"-?\d+\.\d+(?:E[+-]?\d+)?", line,
            )
        ]
        if len(value_positions) != len(current_ids):
            return
        bounds = value_positions + [len(line)]
        norm_key = _normalize_property_key(full_label)
        for idx, sid in enumerate(current_ids):
            start = bounds[idx]
            end = bounds[idx + 1]
            slice_ = line[start:end].strip()
            val = _parse_numeric_or_none(slice_)
            if val is None:
                continue
            target = get_or_init(sid)
            sub = target["properties"].setdefault(current_subsection, {})
            sub[norm_key] = val

    for line in lines:
        upper = line.upper().strip()
        # 进入 REFINERY 段
        if _REFINERY_HEADER_RE.match(line):
            in_refinery = True
            reset_page_state()
            continue
        # 退出：进入另一段头
        if in_refinery and (
            _TBPASTM_HEADER_RE.match(line)
            or upper.startswith("STREAM SUMMARY")
            or upper.startswith("STREAM MOLAR")
            or upper.startswith("STREAM WEIGHT")
            or upper.startswith("***")
            or "COMPONENT DATA" in upper
        ):
            in_refinery = False
            reset_page_state()
            continue
        if not in_refinery:
            continue
        # 页分隔（form feed）→ 仅清空 current_ids
        if "\f" in line:
            reset_page_state()
            continue
        # STREAM ID 行
        m = stream_id_re.match(line)
        if m:
            after = m.group(1)
            ids = re.findall(r"\S+", after)
            if ids:
                current_ids = ids
                positions = [line.find(sid) for sid in ids]
                sorted_pairs = sorted(zip(positions, ids, strict=True))
                id_positions = [p for p, _ in sorted_pairs]
                current_ids = [sid for _, sid in sorted_pairs]
                current_phase = [None] * len(current_ids)
                current_thermo = [None] * len(current_ids)
                needs_recalibration = True
            continue
        # 数值行重校列起点：PRO/II STREAM ID 位置与数据列起点不严格对齐
        # （ID 在列内左侧，数据右对齐），用首个数值行（TEMPERATURE/RATE）
        # 的实际数值起点作为列起点真值。
        if (
            needs_recalibration
            and current_ids
            and re.match(r"^\s+(TEMPERATURE|PRESSURE|RATE|ENTHALPY|MW|MOLECULAR)\b", upper)
            and not upper.startswith("PHASE")
            and not upper.startswith("THERMO ID")
        ):
            positions_found = [
                mm.start() for mm in re.finditer(
                    r"-?\d+\.\d+(?:E[+-]?\d+)?", line,
                )
            ]
            if len(positions_found) == len(current_ids):
                id_positions = positions_found
                needs_recalibration = False
        if name_re.match(line):
            continue
        if phase_re.match(line):
            phase_starts = _detect_phase_column_starts(line, len(current_ids))
            phase_values = _split_phase_row_by_columns(line, phase_starts)
            for idx, p in enumerate(phase_values):
                if idx < len(current_phase) and p:
                    current_phase[idx] = p
            continue
        if thermo_re.match(line):
            thermo_starts = _detect_phase_column_starts(line, len(current_ids))
            thermo_values = _split_phase_row_by_columns(line, thermo_starts)
            for idx, t in enumerate(thermo_values):
                if idx < len(current_thermo) and t:
                    current_thermo[idx] = t.upper().strip()
            continue
        # 子段头
        sub_m = _REFINERY_SUBSECTION_RE.match(line)
        if sub_m:
            current_subsection = _detect_section_label(line)
            continue
        # 子段头
        sub_m = _REFINERY_SUBSECTION_RE.match(line)
        if sub_m:
            current_subsection = _detect_section_label(line)
            continue
        # 属性行：必须有 current_subsection
        if current_subsection and current_ids:
            parse_refinery_property_line(line)

    # 简化：从 streams 收集 last_seen phase/thermo（重新扫描）
    last_phase: dict[str, str] = {}
    last_thermo: dict[str, str] = {}
    in_refinery = False
    current_ids = []
    current_phase = []
    current_thermo = []
    id_positions = []
    needs_recalibration = False
    for line in lines:
        upper = line.upper().strip()
        if _REFINERY_HEADER_RE.match(line):
            in_refinery = True
            current_ids = []
            current_phase = []
            current_thermo = []
            id_positions = []
            needs_recalibration = False
            continue
        if in_refinery and (
            _TBPASTM_HEADER_RE.match(line)
            or upper.startswith("STREAM SUMMARY")
            or upper.startswith("STREAM MOLAR")
            or upper.startswith("STREAM WEIGHT")
            or upper.startswith("***")
            or "COMPONENT DATA" in upper
        ):
            in_refinery = False
            continue
        if not in_refinery:
            continue
        if "\f" in line:
            current_ids = []
            current_phase = []
            current_thermo = []
            id_positions = []
            needs_recalibration = False
            continue
        m = stream_id_re.match(line)
        if m:
            after = m.group(1)
            ids = re.findall(r"\S+", after)
            if ids:
                current_ids = ids
                positions = [line.find(sid) for sid in ids]
                sorted_pairs = sorted(zip(positions, ids, strict=True))
                id_positions = [p for p, _ in sorted_pairs]
                current_ids = [sid for _, sid in sorted_pairs]
                current_phase = [None] * len(current_ids)
                current_thermo = [None] * len(current_ids)
                needs_recalibration = True
            continue
        # 数据行重校（与第一轮一致）
        if (
            needs_recalibration
            and current_ids
            and re.match(r"^\s+(TEMPERATURE|PRESSURE|RATE|ENTHALPY|MW|MOLECULAR)\b", upper)
            and not upper.startswith("PHASE")
            and not upper.startswith("THERMO ID")
        ):
            positions_found = [
                mm.start() for mm in re.finditer(
                    r"-?\d+\.\d+(?:E[+-]?\d+)?", line,
                )
            ]
            if len(positions_found) == len(current_ids):
                id_positions = positions_found
                needs_recalibration = False
        if phase_re.match(line):
            phase_starts = _detect_phase_column_starts(line, len(current_ids))
            phase_values = _split_phase_row_by_columns(line, phase_starts)
            for idx, p in enumerate(phase_values):
                if idx < len(current_phase) and p:
                    current_phase[idx] = p
            continue
        if thermo_re.match(line):
            thermo_starts = _detect_phase_column_starts(line, len(current_ids))
            thermo_values = _split_phase_row_by_columns(line, thermo_starts)
            for idx, t in enumerate(thermo_values):
                if idx < len(current_thermo) and t:
                    current_thermo[idx] = t.upper().strip()
            continue
        # 记录到 last_seen
        for sid, p, t in zip(current_ids, current_phase, current_thermo, strict=False):
            if p:
                last_phase[sid] = p
            if t:
                last_thermo[sid] = t

    result = []
    for sid, s in streams.items():
        s["phase"] = last_phase.get(sid) or s.get("phase")
        s["thermo_id"] = last_thermo.get(sid) or s.get("thermo_id")
        result.append(s)
    return result


def _parse_tbp_astm_curves(text: str) -> list[dict]:
    """STREAM TBP/ASTM CURVES 段解析（FCC 报告专属，SIM-20d）。

    每条 dict：
        stream_id        str
        curve_name       str（TBP / ASTM D86 / ASTM D1160 / ASTM D2887）
        pressure_label   str（'760 MM HG' / '10 MM HG'）
        percent_basis    str（'LV' / 'WT'）—— D86/D1160 是 LV%，D2887 是 WT%
        points           list[{percent: float, temp_c: float | None}]
                          包含标准 cut points 1/5/10/30/50/70/90/95/98。

    跨页同 (stream_id, curve_name, pressure_label) 合并（first non-None wins）。
    负温度原样保留（gas stream 1FLUEGAS 实测 -252.760°C）。
    N/A / 空保持 None（不视作 0）。

    Returns:
        list[dict]；空 list 表示 .out 不含 TBP/ASTM 段。
    """
    lines = text.splitlines()
    curves: dict[tuple[str, str, str], dict] = {}
    in_section = False
    current_ids: list[str] = []
    id_positions: list[int] = []
    current_curve: str | None = None  # 'TBP' / 'ASTM D86' / ...
    current_pressure: str | None = None  # '760 MM HG' / '10 MM HG'
    current_basis: str = "LV"  # 默认 LV；D2887 在 curve header 后会切到 WT

    def get_or_init(sid: str) -> dict:
        if current_curve is None or current_pressure is None:
            return None  # type: ignore[return-value]
        key = (sid, current_curve, current_pressure)
        if key not in curves:
            curves[key] = {
                "stream_id": sid,
                "curve_name": current_curve,
                "pressure_label": current_pressure,
                "percent_basis": current_basis,
                "points": [],
            }
        return curves[key]

    def extract_values(line: str) -> list[float | None]:
        if not current_ids:
            return []
        out: list[float | None] = []
        for idx in range(len(current_ids)):
            start = id_positions[idx]
            end = (
                id_positions[idx + 1]
                if idx + 1 < len(id_positions)
                else len(line)
            )
            slice_ = line[start:end].strip() if start < len(line) else ""
            out.append(_parse_numeric_or_none(slice_))
        return out

    stream_id_re = re.compile(r"^\s+STREAM ID\s+(.+)$", re.IGNORECASE)

    for line in lines:
        upper = line.upper().strip()
        if _TBPASTM_HEADER_RE.match(line):
            in_section = True
            current_ids = []
            id_positions = []
            current_curve = None
            current_pressure = None
            current_basis = "LV"
            continue
        if in_section and (
            _REFINERY_HEADER_RE.match(line)
            or upper.startswith("STREAM SUMMARY")
            or upper.startswith("STREAM MOLAR")
            or upper.startswith("STREAM WEIGHT")
            or upper.startswith("***")
            or "COMPONENT DATA" in upper
        ):
            in_section = False
            current_ids = []
            id_positions = []
            current_curve = None
            current_pressure = None
            continue
        if not in_section:
            continue
        if "\f" in line:
            current_ids = []
            id_positions = []
            current_curve = None
            current_pressure = None
            current_basis = "LV"
            continue
        m = stream_id_re.match(line)
        if m:
            after = m.group(1)
            ids = re.findall(r"\S+", after)
            if ids:
                current_ids = ids
                positions = [line.find(sid) for sid in ids]
                sorted_pairs = sorted(zip(positions, ids, strict=True))
                id_positions = [p for p, _ in sorted_pairs]
                current_ids = [sid for _, sid in sorted_pairs]
            continue
        # 曲线头：'   TBP AT 760 MM HG' / '   ASTM D86 AT 760 MM HG WITH CRACKING'
        # 提取曲线名 + 压力 + basis
        curve_m = _TBPASTM_CURVE_RE.match(line)
        if curve_m and (
            "MM HG" in upper or "WITH CRACKING" in upper
        ):
            raw_curve = curve_m.group(1).strip().upper()
            # 归一化曲线名（去多余空白）
            if raw_curve.startswith("TBP"):
                current_curve = "TBP"
            elif raw_curve.startswith("ASTM"):
                # 提取 ASTM D<num>（如 'ASTM D86' / 'ASTM D1160'）
                astm_m = re.match(r"(ASTM\s+D\d+)", raw_curve)
                current_curve = astm_m.group(1) if astm_m else raw_curve
            else:
                current_curve = raw_curve
            # 提取压力（'AT 760 MM HG' / 'AT 10 MM HG'）
            press_m = re.search(r"AT\s+(\d+\s+MM\s+HG)", upper)
            current_pressure = (
                re.sub(r"\s+", " ", press_m.group(1)) if press_m else "760 MM HG"
            )
            # basis：D2887 是 WT%，其余是 LV%（与 FIRST LV PERCENT / FIRST WT PERCENT 对应）
            if current_curve == "ASTM D2887":
                current_basis = "WT"
            else:
                current_basis = "LV"
            continue
        # 百分位行：'         1 LV PERCENT' / '         5' / '         1 WT PERCENT'
        # 提取 percent 数值；basis 由 'LV PERCENT' / 'WT PERCENT' 决定
        pct_m = re.match(r"^\s*(\d+)\s*(LV\s*PERCENT|WT\s*PERCENT)?\b", upper)
        if pct_m and current_ids and current_curve and current_pressure:
            percent = int(pct_m.group(1))
            basis_label = pct_m.group(2)
            if basis_label:
                current_basis = "WT" if "WT" in basis_label.upper() else "LV"
            values = extract_values(line)
            # 占位行（仅 percent label，无数据）跳过
            if not any(v is not None for v in values) and percent not in {
                1, 5, 10, 30, 50, 70, 90, 95, 98,
            }:
                continue
            for sid, val in zip(current_ids, values, strict=False):
                key = (sid, current_curve, current_pressure)
                if key not in curves:
                    curves[key] = {
                        "stream_id": sid,
                        "curve_name": current_curve,
                        "pressure_label": current_pressure,
                        "percent_basis": current_basis,
                        "points": [],
                    }
                curves[key]["points"].append({
                    "percent": float(percent),
                    "temp_c": val,
                })

    # 仅保留每个 (stream, curve, pressure) 的标准 9 个 cut points
    expected_percents = {1, 5, 10, 30, 50, 70, 90, 95, 98}
    result = []
    for c in curves.values():
        points = c["points"]
        # 同一 stream+curve+pressure 跨多页时合并（去重 percent；first non-None wins）
        seen: dict[float, dict] = {}
        for p in points:
            if p["percent"] not in seen:
                seen[p["percent"]] = p
            elif seen[p["percent"]]["temp_c"] is None and p["temp_c"] is not None:
                seen[p["percent"]]["temp_c"] = p["temp_c"]
        # 排序 + 仅保留 cut points
        merged = [
            seen[pct] for pct in sorted(seen.keys()) if int(pct) in expected_percents
        ]
        # 仅保留至少 1 个有效点的曲线
        if merged:
            c["points"] = merged
            result.append(c)
    return result
