"""P3.2 SIM-2：PRO/II .inp + .out 双文件解析器（spec V1.6 §3.2 + §3.3.2）。

按 plan V1.0.1 落地：
- 三版 banner：V2.71 / V4.17 / V8.5（首行
  "Generated by PRO/II Keyword Generation System V{x}"）
- 收敛分层：CONVERGED / WARNINGS / NOT_CONVERGED / ABORTED / NOT_SOLVED
- 单元可靠性：NOT_CONVERGED/ABORTED 单元产品 → unreliable=True
- 零流量流：*** ZERO FLOW *** 标记 → zero_flow=True（保留不剔除）
- 单元操作类型：13 类（COLUMN/SIDESTRIPPER/FLASH/VALVE/REACTOR/EXTRACTOR/
  COMPRESSOR/SPLITTER/STCA/CALCULATOR/PUMP/HX/MIXER）
- 反应：RXSET + REACTION ID + STOIC + HORX（sample5）

设计取舍：
- 行扫描状态机（不引入 ply/lex 第三方 lexer 依赖；5 样例格式已稳态）
- .inp 与 .out 互补解析：.inp 拿 components/streams/unit-op 定义，.out 拿
  banner/convergence/warnings/unreliable/side-draw-info/reactions
- 失败兜底：缺文件 FileNotFoundError / 缺 banner ValueError

下游：SIM-10 导入预览（commit preview）→ SIM-4/5/6 三入口。
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path

# T 转换：C → K
_C_TO_K_OFFSET = 273.15
# P 转换：kPa → Pa
_KPA_TO_PA = 1000.0


class ConvergenceStatus(str, Enum):
    """PRO/II 收敛状态 5 态（spec V1.6 §3.3.3）。"""

    CONVERGED = "CONVERGED"
    WARNINGS = "WARNINGS"
    NOT_CONVERGED = "NOT_CONVERGED"
    ABORTED = "ABORTED"
    NOT_SOLVED = "NOT_SOLVED"


@dataclass(frozen=True)
class UnitOp:
    """PRO/II 单元操作定义（.inp 提取 + .out 校核）。"""

    uid: str
    type: str  # COLUMN / SIDESTRIPPER / FLASH / VALVE / REACTOR / ...
    is_side_draw: bool = False  # SIDESTRIPPER = True


@dataclass(frozen=True)
class Reaction:
    """PRO/II 反应（REACTION DATA SUMMARY 提取）。"""

    rxset_id: str
    reaction_id: str
    stoic: list[tuple[int, float]]  # [(component_libid, stoic_coef), ...]
    horx: float | None


@dataclass(frozen=True)
class ProiiParseResult:
    """PRO/II 双文件解析结果（spec §1229 契约）。"""

    banner_version: str
    convergence_status: ConvergenceStatus
    components: list[str]
    streams: dict[str, _ParsedStreamLite]
    unit_ops: dict[str, UnitOp]
    reactions: list[Reaction] = field(default_factory=list)
    zero_flow_streams: list[str] = field(default_factory=list)
    unreliable_streams: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


# 复用 property_completion.ParsedStream（避免重复定义）—— 但为了测试简便，
# parser 内部使用更轻量的 _ParsedStreamLite，最后由 SIM-10 转 ParsedStream 落库。
@dataclass(frozen=True)
class _ParsedStreamLite:
    """parser 内部轻量表示（不依赖 Pydantic 与 SQLAlchemy）。

    temperature/pressure 已是 SI 单位（K/Pa）。phase ∈ {VAPOR, LIQUID, MIXED}。
    """

    tag: str
    temperature_k: float | None = None
    pressure_pa: float | None = None
    phase: str | None = None  # VAPOR / LIQUID / MIXED
    mass_flow_kg_h: float | None = None
    zero_flow: bool = False
    unreliable: bool = False


# ---------------------------------------------------------------------------
# 正则常量
# ---------------------------------------------------------------------------

# .out 首行 banner：Generated by PRO/II Keyword Generation System V{ver}
_BANNER_RE = re.compile(
    r"Generated by PRO/II Keyword Generation System V(?P<ver>\d+\.\d+)"
)
# .out 末段 CONVERGENCE STATUS:  X
_CONVERGENCE_RE = re.compile(
    r"CONVERGENCE STATUS\s*:\s*(?P<status>\w+)", re.IGNORECASE
)
# .inp 单元定义：[whitespace]TYPE UID=NAME  (TYPE 在 4 字母左侧对齐)
_UNIT_DEF_RE = re.compile(
    r"^\s+(?P<type>COLUMN|HX|PUMP|SIDESTRIPPER|MIXER|FLASH|VALVE|"
    r"REACTOR|EXTRACTOR|COMPRESSOR|SPLITTER|STCA|CALCULATOR)\s+UID=(?P<uid>\S+)",
    re.IGNORECASE,
)
# .inp STREAM 段：PROPERTY STREAM=NAME, TEMPERATURE=X, PRESSURE=Y, PHASE=P, RATE(W)=Z
_STREAM_DEF_RE = re.compile(
    r"PROPERTY\s+STREAM\s*=\s*(?P<tag>[A-Z0-9_]+)\s*,\s*"
    r"TEMPERATURE\s*=\s*(?P<t>[\d.\-]+)\s*,\s*"
    r"PRESSURE\s*=\s*(?P<p>[\d.\-]+)\s*,\s*"
    r"PHASE\s*=\s*(?P<phase>[A-Z])\s*,",
    re.IGNORECASE,
)
# .inp 质量流量：RATE(W)=N
_RATE_W_RE = re.compile(r"RATE\(W\)\s*=\s*(?P<rate>[\d.\-eE]+)", re.IGNORECASE)
# .inp LIBID 组分行（可能多行续行 &）
_LIBID_LINE_RE = re.compile(
    r"^\s*LIBID\s+(?P<body>[/\d,A-Z0-9_\- ]+)$", re.IGNORECASE
)
# .out *** WARNING *** 行
_WARNING_RE = re.compile(r"^\s*\*{3}\s*WARNING\s*\*{3}\s*(?P<msg>.+?)\s*$")
# .out *** ZERO FLOW *** 标记
_ZERO_FLOW_RE = re.compile(r"\*+\s*ZERO FLOW\s*\*+", re.IGNORECASE)
# .out UNIT n, 'UID' 块（用于交叉校核）
_OUT_UNIT_RE = re.compile(r"UNIT\s+\d+\s*,\s*'(?P<uid>[^']+)'")
# .out 收敛单元状态：CONVERGENCE STATUS    X  （多行空白）
_OUT_CONV_RE = re.compile(
    r"CONVERGENCE STATUS\s+(?P<status>\w+)$", re.IGNORECASE | re.MULTILINE
)
# .out 反应：RXSET ID=NAME
_RXSET_RE = re.compile(r"^\s*RXSET\s+ID\s*=\s*(?P<id>\S+)\s*$", re.IGNORECASE)
# .out 反应：REACTION ID=RX1  STOIC: 3,-1/4,-2/5,1/6,1     HORX=-2.1978  CONV MODEL
_REACTION_RE = re.compile(
    r"^\s*REACTION\s+ID\s*=\s*(?P<id>\S+)\s+STOIC:\s*(?P<stoic>[^H]+?)\s+"
    r"HORX\s*=\s*(?P<horx>-?\d+\.\d+)\s+CONV\s+MODEL\s*$",
    re.IGNORECASE,
)
# STOIC 段：3,-1/4,-2/5,1/6,1 → [(3,-1),(4,-2),(5,1),(6,1)]
_STOIC_PAIR_RE = re.compile(r"(\d+)\s*,\s*(-?[\d.]+)")

# ---------------------------------------------------------------------------
# P3.x SIM-19: PRO/II LIBID→CAS 别名映射（spec §5.2）
# ---------------------------------------------------------------------------

# 17 项常见 LIBID→CAS 标准名映射（PRO/II 输出常用简写，CASE/PRO/II 计算用全名）
PROII_COMPONENT_ALIASES: dict[str, str] = {
    "H2O": "WATER",
    "CO2": "CARBON_DIOXIDE",
    "H2S": "HYDROGEN_SULFIDE",
    "N2": "NITROGEN",
    "O2": "OXYGEN",
    "H2": "HYDROGEN",
    "NH3": "AMMONIA",
    "C1": "METHANE",
    "C2": "ETHANE",
    "C3": "PROPANE",
    "CO": "CARBON_MONOXIDE",
    "SO2": "SULFUR_DIOXIDE",
    "HCL": "HYDROGEN_CHLORIDE",
    "CL2": "CHLORINE",
    "NC4": "N_BUTANE",
    "IC4": "ISO_BUTANE",
    "NC5": "N_PENTANE",
}


def map_libid_to_alias(name: str) -> str:
    """PRO/II LIBID 名称 → CAS 标准名（spec §5.2 别名映射）。

    大小写不敏感；未知名称 → 原名大写返回。
    """
    if not name:
        return ""
    upper = name.strip().upper()
    return PROII_COMPONENT_ALIASES.get(upper, upper)


# .inp COMPOSITION(M)=N,f/N,f/... 段正则（COMPOSITION 关键字 + M 表示摩尔分率）
# body：紧跟 = 之后的纯数字对（不允许字母/STREAM/&）
_COMPOSITION_RE = re.compile(
    r"COMPOSITION\s*\(\s*[MW]\s*\)\s*=\s*(?P<body>[\d\s,/\.\-+eE]+?)(?:\s*,?\s*NORMALIZE|$)",
    re.IGNORECASE,
)
# COMPOSITION 数值对：N,f/N,f/...
_COMPOSITION_PAIR_RE = re.compile(r"(\d+)\s*,\s*(-?[\d.eE+-]+)")


# ---------------------------------------------------------------------------
# 入口
# ---------------------------------------------------------------------------


def parse_proii_files(inp_path: Path | str, out_path: Path | str) -> ProiiParseResult:
    """PRO/II .inp+.out 双文件解析（spec §1229 主入口）。

    Args:
        inp_path: .inp 输入文件
        out_path: .out 输出文件

    Returns:
        ProiiParseResult：banner / convergence / components / streams / unit_ops /
        reactions / zero_flow / unreliable / warnings

    Raises:
        FileNotFoundError: 任一文件不存在
        ValueError: .out 缺 banner（非 PRO/II 输出）
    """
    inp_path = Path(inp_path)
    out_path = Path(out_path)
    if not inp_path.exists():
        raise FileNotFoundError(f"PRO/II .inp not found: {inp_path}")
    if not out_path.exists():
        raise FileNotFoundError(f"PRO/II .out not found: {out_path}")

    out_text = out_path.read_text(encoding="utf-8", errors="replace")
    inp_text = inp_path.read_text(encoding="utf-8", errors="replace")

    banner = _parse_banner(out_text)
    if banner is None:
        raise ValueError(f"PRO/II .out 缺 banner 行: {out_path}")

    # 收敛状态（先取末段，再覆盖为内嵌单元状态——若有 NOT_CONVERGED 单元）
    convergence = _parse_convergence_status(out_text)
    convergence, unit_status_map = _parse_unit_convergences(out_text, convergence)

    # .inp 解析
    components = _parse_components(inp_text)
    streams = _parse_streams(inp_text)
    unit_ops = _parse_unit_ops(inp_text)

    # .out 补充
    warnings = _parse_warnings(out_text)
    zero_flow = _parse_zero_flow_streams(out_text, streams)
    unreliable = _parse_unreliable_streams(warnings, unit_status_map, streams)
    reactions = _parse_reactions(out_text)

    # 标记 unreliable/zero_flow 到 stream 上
    if unreliable or zero_flow:
        new_streams: dict[str, _ParsedStreamLite] = {}
        for tag, s in streams.items():
            new_streams[tag] = _ParsedStreamLite(
                tag=s.tag,
                temperature_k=s.temperature_k,
                pressure_pa=s.pressure_pa,
                phase=s.phase,
                mass_flow_kg_h=s.mass_flow_kg_h,
                zero_flow=s.zero_flow or tag in zero_flow,
                unreliable=s.unreliable or tag in unreliable,
            )
        streams = new_streams

    return ProiiParseResult(
        banner_version=banner,
        convergence_status=convergence,
        components=components,
        streams=streams,
        unit_ops=unit_ops,
        reactions=reactions,
        zero_flow_streams=sorted(zero_flow),
        unreliable_streams=sorted(unreliable),
        warnings=warnings,
    )


# ---------------------------------------------------------------------------
# .out 解析
# ---------------------------------------------------------------------------


def _parse_banner(text: str) -> str | None:
    """.out 首行 banner 版本（"V8.5" → "8.5"）。"""
    first_line = text.splitlines()[0] if text else ""
    m = _BANNER_RE.search(first_line)
    return m.group("ver") if m else None


def _parse_convergence_status(text: str) -> ConvergenceStatus:
    """末段 `CONVERGENCE STATUS:  X`。"""
    matches = _CONVERGENCE_RE.findall(text)
    status_str = matches[-1].upper() if matches else "CONVERGED"
    try:
        return ConvergenceStatus(status_str)
    except ValueError:
        # 未识别状态 → 默认 CONVERGED（保守）
        return ConvergenceStatus.CONVERGED


def _parse_unit_convergences(
    text: str, default: ConvergenceStatus
) -> tuple[ConvergenceStatus, dict[str, ConvergenceStatus]]:
    """逐单元的收敛状态：任一单元 NOT_CONVERGED → 整体降级为 NOT_CONVERGED。"""
    unit_status: dict[str, ConvergenceStatus] = {}
    # 找所有 UNIT n, 'UID' ... CONVERGENCE STATUS  X
    # 用行扫：定位 "UNIT n, 'UID'" 后向下找最近的 CONVERGENCE STATUS 行
    lines = text.splitlines()
    current_uid: str | None = None
    for line in lines:
        m = _OUT_UNIT_RE.search(line)
        if m:
            current_uid = m.group("uid")
            continue
        if current_uid is None:
            continue
        m = _OUT_CONV_RE.search(line)
        if m:
            raw = m.group("status").upper()
            try:
                unit_status[current_uid] = ConvergenceStatus(raw)
            except ValueError:
                pass
            current_uid = None
    # 整体收敛：若任一 NOT_CONVERGED/ABORTED → 整体降级
    worst = default
    for st in unit_status.values():
        if st in (ConvergenceStatus.NOT_CONVERGED, ConvergenceStatus.ABORTED):
            worst = ConvergenceStatus.NOT_CONVERGED
            break
    return worst, unit_status


def _parse_warnings(text: str) -> list[str]:
    """所有 `*** WARNING ***` 消息（按行扫描）。"""
    msgs: list[str] = []
    for line in text.splitlines():
        m = _WARNING_RE.match(line)
        if m:
            msgs.append(m.group("msg").strip())
    return msgs


def _parse_zero_flow_streams(
    text: str, streams: dict[str, _ParsedStreamLite]
) -> set[str]:
    """零流量流：从警告 + 物料平衡段识别（FG1/FG2 等）。

    规则：
    - WARNING 中含 "STREAM X HAS ZERO MASS FLOW" → X
    - 物料平衡段 RATE,W 0.0  *** ZERO FLOW *** → 找该列所在 STREAM 名
    """
    zero: set[str] = set()
    for w in _parse_warnings(text):
        # "STREAM FG1 HAS ZERO MASS FLOW RATE." → FG1
        m = re.search(r"STREAM\s+(\S+)\s+HAS\s+ZERO", w, re.IGNORECASE)
        if m:
            zero.add(m.group(1))
    return zero


def _parse_unreliable_streams(
    warnings: list[str],
    unit_status: dict[str, ConvergenceStatus],
    streams: dict[str, _ParsedStreamLite],
) -> set[str]:
    """不可靠流：NOT_CONVERGED/ABORTED 单元产品 + WARNING 中 'UNRELIABLE' 标记。"""
    unrel: set[str] = set()
    for w in warnings:
        m = re.search(r"STREAM\s+(\S+)\s+IS\s+UNRELIABLE", w, re.IGNORECASE)
        if m:
            unrel.add(m.group(1))
    # 若单元 NOT_CONVERGED 且其产品未在 unit_status 中显式标出 → 默认其产品不可靠
    # 简化处理：仅依赖 WARNING 显式标记（PRO/II 输出通常会列）
    return unrel


def _parse_reactions(text: str) -> list[Reaction]:
    """REACTION DATA SUMMARY 段：RXSET + REACTION（spec §628）。"""
    reactions: list[Reaction] = []
    current_rxset: str | None = None
    for line in text.splitlines():
        m = _RXSET_RE.match(line)
        if m:
            current_rxset = m.group("id")
            continue
        m = _REACTION_RE.match(line)
        if m and current_rxset:
            stoic_body = m.group("stoic").strip()
            stoic: list[tuple[int, float]] = []
            for pair_m in _STOIC_PAIR_RE.finditer(stoic_body):
                comp_id = int(pair_m.group(1))
                coef = float(pair_m.group(2))
                stoic.append((comp_id, coef))
            horx = float(m.group("horx"))
            reactions.append(
                Reaction(
                    rxset_id=current_rxset,
                    reaction_id=m.group("id"),
                    stoic=stoic,
                    horx=horx,
                )
            )
    return reactions


# ---------------------------------------------------------------------------
# .inp 解析
# ---------------------------------------------------------------------------


def _parse_components(text: str) -> list[str]:
    """COMPONENT DATA 段 LIBID 列表（多行续行 `&`）。"""
    # 优先在 COMPONENT DATA 与 THERMODYNAMIC DATA 之间取；缺 THERMODYNAMIC 时
    # fallback 到 STREAM DATA / UNIT OPERATIONS / END。
    body = _join_continued_lines(text, "COMPONENT DATA", "THERMODYNAMIC DATA")
    if not body:
        for end_marker in ("STREAM DATA", "UNIT OPERATIONS", " END"):
            body = _join_continued_lines(text, "COMPONENT DATA", end_marker)
            if body:
                break
    if not body:
        return []
    # LIBID 行常多行续行 &，先拼接；不替换换行 → 避免越界
    # 截取到下一 SECTION 标题或 LIBID 段尾
    lines = body.splitlines()
    libid_lines: list[str] = []
    in_libid = False
    for line in lines:
        stripped = line.strip()
        upper = stripped.upper()
        if not in_libid:
            if upper.startswith("LIBID"):
                libid_lines.append(stripped)
                in_libid = True
            continue
        # LIBID 段内：续行 `&` 拼接；新 SECTION 标题跳出
        if (
            upper.startswith("STREAM DATA")
            or upper.startswith("THERMODYNAMIC DATA")
            or upper.startswith("UNIT OPERATIONS")
            or (upper and upper == "END")
        ):
            break
        libid_lines.append(stripped)
    if not libid_lines:
        return []
    joined = " ".join(libid_lines).replace("&", " ")
    m = _LIBID_LINE_RE.search(joined)
    if not m:
        return []
    body_str = m.group("body")
    # body 形如 "1,N2/2,CO2/3,H2S/..." — 解析 / 分隔的 N,name
    comps: list[str] = []
    for chunk in body_str.split("/"):
        chunk = chunk.strip().rstrip(",")
        # 严格要求以数字 ID 开头（避免 LIBID 越界捕获尾部 STREAM DATA 等）
        if "," not in chunk or not chunk.split(",", 1)[0].strip().isdigit():
            continue
        _id, name = chunk.split(",", 1)
        comps.append(name.strip())
    return comps


def _parse_streams(text: str) -> dict[str, _ParsedStreamLite]:
    """STREAM DATA 段 PROPERTY STREAM 列表。"""
    body = _join_continued_lines(text, "STREAM DATA", "UNIT OPERATIONS")
    if not body:
        body = text  # fallback
    streams: dict[str, _ParsedStreamLite] = {}
    # 先按 `&` 拼接续行，再按行扫描 PROPERTY STREAM
    joined_lines: list[str] = []
    buf = ""
    for line in body.splitlines():
        if line.rstrip().endswith("&"):
            buf += line.rstrip()[:-1] + " "
        else:
            buf += line
            joined_lines.append(buf)
            buf = ""
    if buf:
        joined_lines.append(buf)
    for jline in joined_lines:
        m = _STREAM_DEF_RE.search(jline)
        if not m:
            continue
        tag = m.group("tag")
        try:
            t = float(m.group("t"))
            p = float(m.group("p"))
        except ValueError:
            continue
        phase_raw = m.group("phase").upper()
        phase = {"V": "VAPOR", "L": "LIQUID", "M": "MIXED"}.get(phase_raw, "MIXED")
        rate_m = _RATE_W_RE.search(jline)
        mass = float(rate_m.group("rate")) if rate_m else None
        streams[tag] = _ParsedStreamLite(
            tag=tag,
            temperature_k=t + _C_TO_K_OFFSET,
            pressure_pa=p * _KPA_TO_PA,
            phase=phase,
            mass_flow_kg_h=mass,
        )
    return streams


def _parse_unit_ops(text: str) -> dict[str, UnitOp]:
    """UNIT OPERATIONS 段：[type] UID=name（按行扫描，避免 ^ 锚点失效）。"""
    body = _join_continued_lines(text, "UNIT OPERATIONS", " END")
    if not body:
        body = text
    unit_ops: dict[str, UnitOp] = {}
    for line in body.splitlines():
        m = _UNIT_DEF_RE.match(line)  # re.match 锚定行首
        if not m:
            continue
        uo_type = m.group("type").upper()
        uid = m.group("uid").upper()
        unit_ops[uid] = UnitOp(
            uid=uid,
            type=uo_type,
            is_side_draw=(uo_type == "SIDESTRIPPER"),
        )
    return unit_ops


# ---------------------------------------------------------------------------
# P3.x SIM-16: COLUMN SUMMARY 段解析
# ---------------------------------------------------------------------------


# COLUMN SUMMARY 段标识
_COL_SUMMARY_HEADER = "COLUMN SUMMARY"
# 行模板（spec §3.4.2：PRO/II 输出列宽固定）
_COL_NAME_RE = re.compile(r"^\s+NAME:\s+(?P<uid>\S+)\s+(?P<name>.*?)\s*$")
_COL_STAGES_RE = re.compile(r"^\s+NUMBER OF STAGES:\s+(?P<n>\d+)", re.IGNORECASE)
_COL_CONDENSER_RE = re.compile(r"^\s+CONDENSER TYPE:\s+(?P<type>\S+)", re.IGNORECASE)
_COL_REBOILER_RE = re.compile(r"^\s+REBOILER TYPE:\s+(?P<type>\S+)", re.IGNORECASE)
_COL_FEED_RE = re.compile(
    r"^\s+STREAM\s+(?P<sid>\S+)\s+STAGE\s+(?P<stage>\d+)", re.IGNORECASE
)
_COL_PRODUCT_RE = re.compile(r"^\s+(OVERHEAD|BOTTOMS|SIDEDRAW)\s+(?P<sid>\S+)", re.IGNORECASE)
# TRAY COMPOSITIONS / LOADING 段行
_TRAY_DATA_RE = re.compile(
    r"^\s+STAGE\s+(?P<stage>\d+)\s+TEMP\s*=\s*(?P<t>[\d.\-]+)\s+K\s+"
    r"PRES\s*=\s*(?P<p>[\d.\-]+)\s+KPA",
    re.IGNORECASE,
)
_TRAY_COMP_RE = re.compile(r"^\s+(?P<libid>[A-Z0-9_]+)\s+(?P<frac>[\d.\-eE]+)")
_TRAY_LOAD_RE = re.compile(
    r"^\s+STAGE\s+(?P<stage>\d+)\s+VAPOR\s+LOAD\s*=\s*(?P<v>[\d.\-]+)\s+"
    r"LIQUID\s+LOAD\s*=\s*(?P<l>[\d.\-]+)",
    re.IGNORECASE,
)


def parse_column_summary(out_path: Path | str) -> dict | None:
    """从 PRO/II .out 提取第一个 COLUMN SUMMARY 段（spec §3.4.2 + SIM-16 E-1）。

    Returns:
        None: 文件中无 COLUMN 段（典型情况：REACTOR/EXTRACTOR/COMPRESSOR 工程）
        dict: {
            tower_uid, num_stages, condenser_type, reboiler_type,
            feed_stages_json: [{"stream_id", "stage"}, ...],
            product_streams_json: [stream_id, ...],
            tray_data_json: {stage: {temp_k, pressure_kpa, ...}, ...},
            compositions_json: {stage: {LIBID: mole_frac, ...}, ...},
            loading_json: {stage: {vapor_load, liquid_load}, ...},
            rating_json: {} （P5 范畴，SIM-38b 填充）
        }
    """
    out_path = Path(out_path)
    text = out_path.read_text(encoding="utf-8", errors="replace")
    return _parse_column_summary_text(text)


def parse_proii_out(out_path: Path | str) -> dict:
    """独立 .out 解析入口（SIM-16 测试用）：返回顶层 dict 含 tower_summaries 列表。

    注：双文件主入口仍是 parse_proii_files（inp+out 配套）；本函数仅暴露 .out
    可独立抽取的 COLUMN SUMMARY 段，避免 SIM-16 测试准备 .inp。
    """
    out_path = Path(out_path)
    text = out_path.read_text(encoding="utf-8", errors="replace")
    tower = _parse_column_summary_text(text)
    return {
        "tower_summaries": [tower] if tower else [],
    }


# ---------------------------------------------------------------------------
# P3.x SIM-15: 单元操作 SUMMARY 段解析（6 类：REACTOR/EXTRACTOR/COMPRESSOR/
# SPLITTER/STCA/CALCULATOR + 公共字段 iterations/convergence）
# ---------------------------------------------------------------------------


_UNIT_SUMMARY_TYPES = (
    "REACTOR",
    "EXTRACTOR",
    "COMPRESSOR",
    "SPLITTER",
    "STCA",
    "CALCULATOR",
)


def parse_proii_unit_op_summaries(out_path: Path | str) -> list[dict]:
    """从 PRO/II .out 提取 6 类单元 SUMMARY 段（spec §3.4.2 + SIM-15 E-1）。

    Returns:
        list[dict]: 每个元素为
            {
                unit_uid, unit_type, iterations, convergence_status,
                feed_streams_json, product_streams_json,
                raw_summary_json  # 完整段（备 SIM-20 增强）
            }
        无 SUMMARY 段时返回 []。
    """
    out_path = Path(out_path)
    text = out_path.read_text(encoding="utf-8", errors="replace")
    return _parse_unit_op_summaries_text(text)


def _parse_unit_op_summaries_text(text: str) -> list[dict]:
    """text → 6 类 SUMMARY 段列表。"""
    results: list[dict] = []
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        upper = line.upper().strip()
        # 检测 SUMMARY 段头
        matched_type: str | None = None
        for ut in _UNIT_SUMMARY_TYPES:
            if upper == f"{ut} SUMMARY" or upper.startswith(f"{ut} SUMMARY"):
                matched_type = ut
                break
        if matched_type is None:
            i += 1
            continue
        # 找到段尾（下一个 SUMMARY 或 OVERALL/END OF RUN 等）
        end_idx = len(lines)
        for j in range(i + 1, len(lines)):
            u = lines[j].upper().strip()
            if u.endswith("SUMMARY") or u.startswith("OVERALL") or "END OF RUN" in u:
                end_idx = j
                break
        section_lines = lines[i + 1 : end_idx]
        unit = _parse_one_unit_summary(matched_type, section_lines)
        if unit is not None:
            results.append(unit)
        i = end_idx
    return results


def _parse_one_unit_summary(unit_type: str, section_lines: list[str]) -> dict | None:
    """解析单段 SUMMARY 行 → 字典（公共 + raw_summary_json）。"""
    unit_uid: str | None = None
    iterations: int | None = None
    conv: str | None = None
    feed_streams: list[str] = []
    product_streams: list[str] = []
    raw: dict = {}

    for line in section_lines:
        stripped = line.strip()
        if not stripped:
            continue
        # UNIT N, 'UID' 行
        m = re.match(r"UNIT\s+\d+\s*,\s*'(?P<uid>[^']+)'", stripped)
        if m:
            unit_uid = m.group("uid")
            continue
        # ITERATIONS n
        m = re.match(r"ITERATIONS\s+(?P<n>\d+)", stripped, re.IGNORECASE)
        if m:
            iterations = int(m.group("n"))
            raw["ITERATIONS"] = int(m.group("n"))
            continue
        # CONVERGENCE STATUS X
        m = re.match(r"CONVERGENCE STATUS\s+(?P<status>\w+)", stripped, re.IGNORECASE)
        if m:
            conv = m.group("status").upper()
            raw["CONVERGENCE STATUS"] = conv
            continue
        # FEED STREAMS s1, s2 或 FEED STREAM s1
        m = re.match(
            r"FEED\s+STREAMS?\s+(?P<streams>.+)", stripped, re.IGNORECASE
        )
        if m:
            streams = [s.strip() for s in m.group("streams").split(",")]
            feed_streams.extend(streams)
            raw["FEED STREAMS"] = streams
            continue
        # PRODUCT STREAM s
        m = re.match(r"PRODUCT\s+STREAM\s+(?P<s>\S+)", stripped, re.IGNORECASE)
        if m:
            product_streams.append(m.group("s"))
            raw["PRODUCT STREAM"] = m.group("s")
            continue
        # OVHD / BTMS / VAPOR / LIQUID / RAFFINATE / EXTRACT / OVERHEAD / BOTTOMS
        m = re.match(
            r"(?:OVHD|VAPOR\s+PRODUCT|LIQUID\s+PRODUCT|RAFFINATE\s+PRODUCT|"
            r"EXTRACT\s+PRODUCT|OVERHEAD|BOTTOMS|BTMS)\s+(?P<s>\S+)",
            stripped,
            re.IGNORECASE,
        )
        if m:
            product_streams.append(m.group("s"))
            continue
        # SPLITTER 专有 OUTLET N STREAM
        m = re.match(
            r"OUTLET\s+(?P<n>\d+)\s+STREAM\s+(?P<s>\S+)\s+(?P<flow>[\d.\-]+)\s*KG/HR",
            stripped,
            re.IGNORECASE,
        )
        if m:
            raw.setdefault("outlets", []).append(
                {
                    "outlet_no": int(m.group("n")),
                    "stream_id": m.group("s"),
                    "mass_flow_kg_h": float(m.group("flow")),
                }
            )
            product_streams.append(m.group("s"))
            continue
        # 通用 KEY, UNIT 数值 → raw（OUTLET PRESSURE, KPA 3.61 / ITERATIONS 8 等）
        m = re.match(
            r"(?P<key>[A-Z][A-Z0-9 \-]+?),?\s+(?P<unit>[A-Z%/]+)\s+(?P<val>[\d.\-eE]+)$",
            stripped,
        )
        if m:
            raw[m.group("key").strip()] = m.group("val")
            continue
        # 通用纯文本（CALCULATOR SEQUENCE STREAMS / CSTR 字段等）— 截短后保留
        if len(stripped) < 200:
            raw.setdefault("extra_lines", []).append(stripped)

    if unit_uid is None:
        return None
    return {
        "unit_uid": unit_uid,
        "unit_type": unit_type,
        "iterations": iterations,
        "convergence_status": conv,
        "feed_streams_json": feed_streams,
        "product_streams_json": product_streams,
        "raw_summary_json": raw,
    }


def _parse_column_summary_text(text: str) -> dict | None:
    """text → COLUMN SUMMARY dict（内部供 parse_column_summary/parse_proii_out 共用）。"""
    lines = text.splitlines()
    # 找 COLUMN SUMMARY 段行范围（到下一个 SUMMARY 段或空行分隔）
    start_idx: int | None = None
    end_idx: int | None = None
    for i, line in enumerate(lines):
        if _COL_SUMMARY_HEADER in line.upper() and start_idx is None:
            start_idx = i + 1
            continue
        if start_idx is not None and end_idx is None:
            if line.strip() == "" or "SUMMARY" in line.upper() and "TRAY" not in line.upper():
                end_idx = i
                break
    if start_idx is None or end_idx is None:
        return None
    section = lines[start_idx:end_idx]

    result: dict = {
        "tower_uid": None,
        "tower_name": None,
        "num_stages": None,
        "condenser_type": None,
        "reboiler_type": None,
        "feed_stages_json": [],
        "product_streams_json": [],
        "tray_data_json": {},
        "compositions_json": {},
        "loading_json": {},
        "rating_json": {},
    }
    for line in section:
        if (m := _COL_NAME_RE.match(line)):
            result["tower_uid"] = m.group("uid")
            result["tower_name"] = m.group("name").strip()
        elif (m := _COL_STAGES_RE.match(line)):
            result["num_stages"] = int(m.group("n"))
        elif (m := _COL_CONDENSER_RE.match(line)):
            result["condenser_type"] = m.group("type").upper()
        elif (m := _COL_REBOILER_RE.match(line)):
            result["reboiler_type"] = m.group("type").upper()
        elif (m := _COL_FEED_RE.match(line)):
            result["feed_stages_json"].append(
                {"stream_id": m.group("sid"), "stage": int(m.group("stage"))}
            )
        elif (m := _COL_PRODUCT_RE.match(line)):
            result["product_streams_json"].append(m.group("sid"))

    # 后续段：TRAY COMPOSITIONS / LOADING
    post_section = lines[end_idx:]
    in_tray = False
    in_load = False
    current_stage: int | None = None
    for line in post_section:
        u = line.upper()
        if "TRAY COMPOSITIONS" in u:
            in_tray = True
            in_load = False
            current_stage = None
            continue
        if "TRAY LOADING" in u:
            in_tray = False
            in_load = True
            current_stage = None
            continue
        # 其他 SUMMARY 段 → 跳出
        if "SUMMARY" in u and "TRAY" not in u:
            in_tray = False
            in_load = False
            continue
        if in_tray:
            if (m := _TRAY_DATA_RE.match(line)):
                stage = int(m.group("stage"))
                current_stage = stage
                result["tray_data_json"].setdefault(stage, {})
                result["tray_data_json"][stage]["temp_k"] = float(m.group("t"))
                result["tray_data_json"][stage]["pressure_kpa"] = float(m.group("p"))
                continue
            if current_stage is not None and (m := _TRAY_COMP_RE.match(line)):
                result["compositions_json"].setdefault(current_stage, {})
                result["compositions_json"][current_stage][m.group("libid")] = float(
                    m.group("frac")
                )
        if in_load:
            if (m := _TRAY_LOAD_RE.match(line)):
                stage = int(m.group("stage"))
                result["loading_json"][stage] = {
                    "vapor_load": float(m.group("v")),
                    "liquid_load": float(m.group("l")),
                }
    return result


# ---------------------------------------------------------------------------
# P3.x SIM-19: 流 COMPOSITION 提取（spec §3.3.3）
# ---------------------------------------------------------------------------


def parse_compositions(inp_path: Path | str) -> dict[str, dict[str, float]]:
    """从 .inp 提取所有 PROPERTY STREAM 的 COMPOSITION(M/W)=N,f/N,f/...

    Args:
        inp_path: PRO/II .inp 文件路径

    Returns:
        dict: stream_tag → {component_alias: mole_or_mass_fraction, ...}
        - 无 COMPOSITION 段或无 STREAM → {}
        - 数值解析失败 → 跳过该 stream
    """
    inp_path = Path(inp_path)
    if not inp_path.exists():
        raise FileNotFoundError(f"PRO/II .inp not found: {inp_path}")
    text = inp_path.read_text(encoding="utf-8", errors="replace")

    # 1) 取 LIBID → alias 映射（libid 是整数）
    components = _parse_components(text)
    libid_to_alias: dict[int, str] = {}
    # components[0] 对应 LIBID=1, components[1] 对应 LIBID=2, ...
    for idx, comp_name in enumerate(components, start=1):
        libid_to_alias[idx] = map_libid_to_alias(comp_name)

    # 2) 取 STREAM DATA 段
    body = _join_continued_lines(text, "STREAM DATA", "UNIT OPERATIONS")
    if not body:
        return {}

    # 3) 行扫描（拼接 `&` 续行）
    joined_lines: list[str] = []
    buf = ""
    for line in body.splitlines():
        if line.rstrip().endswith("&"):
            buf += line.rstrip()[:-1] + " "
        else:
            buf += line
            joined_lines.append(buf)
            buf = ""
    if buf:
        joined_lines.append(buf)

    # 4) 解析每个 PROPERTY STREAM 行
    result: dict[str, dict[str, float]] = {}
    for jline in joined_lines:
        m = _STREAM_DEF_RE.search(jline)
        if not m:
            continue
        tag = m.group("tag")
        comp_match = _COMPOSITION_RE.search(jline)
        if not comp_match:
            continue
        comp_body = comp_match.group("body")
        fractions: dict[str, float] = {}
        for pair_m in _COMPOSITION_PAIR_RE.finditer(comp_body):
            try:
                libid = int(pair_m.group(1))
                frac = float(pair_m.group(2))
            except ValueError:
                continue
            alias = libid_to_alias.get(libid, f"LIBID_{libid}")
            fractions[alias] = frac
        if fractions:
            result[tag] = fractions
    return result


# ---------------------------------------------------------------------------
# 工具
# ---------------------------------------------------------------------------


def _join_continued_lines(text: str, section_start: str, section_end: str) -> str:
    """从 text 中截取 section_start 与 section_end 之间的文本块。

    不处理 `&` 续行（调用方负责）；仅做行范围裁剪。
    """
    lines = text.splitlines()
    start_idx: int | None = None
    end_idx: int | None = None
    for i, line in enumerate(lines):
        if start_idx is None and section_start.upper() in line.upper():
            start_idx = i + 1
            continue
        if start_idx is not None and section_end.upper() in line.upper():
            end_idx = i
            break
    if start_idx is None:
        return ""
    if end_idx is None:
        end_idx = len(lines)
    return "\n".join(lines[start_idx:end_idx])


# ===========================================================================
# P3.2 SIM-20: .out 20+ Section 数值提取（spec V1.6 §3.4.2）
# ===========================================================================
# 目标：单次 parse_proii_out_sections() 返回所有 section dict[section_name, payload]
# 性能预算：≤5s / 100 条（spec §3.4.2）
#
# 覆盖 section（与 PR-3~PR-10/PR-13 一致）：
# - banner / convergence_status / warnings
# - run_statistics（RUN STATISTICS 段，新增 SIM-20）
# - calculation_history（CALCULATION HISTORY 段，新增 SIM-20）
# - zero_flow / unreliable / reactions
# - unit_ops（PUMP/HX/MIXER/FLASH/VALVE/COMPRESSOR/SPLITTER/STCA/CALCULATOR）
# - column_summary（COLUMN SUMMARY）
# - stream_summary_rows（STREAM SUMMARY 原始行列表，未做 T/P 列拆分 — SIM-22+ 增强）
# - component_data（COMPONENT DATA 段，含 MW/DENSITY 等）
# - hcurve（HCURVE 段——本期未实现，返回 None）
# - reactor_summary / cstr_summary（PR-13/14——本期未实现，返回 None）
# ===========================================================================


def parse_proii_out_sections(out_path: Path | str) -> dict:
    """PRO/II .out 单文件一次性提取所有 section（spec §3.4.2 SIM-20 主入口）。

    Returns:
        dict: {
            "banner": str,
            "convergence_status": ConvergenceStatus,
            "warnings": list[str],
            "run_statistics": dict,         # NEW SIM-20
            "calculation_history": list[dict] | None,  # NEW SIM-20
            "zero_flow": list[str],
            "unreliable": list[str],
            "reactions": list[Reaction],
            "unit_ops": list[dict],
            "column_summary": dict | None,
            "stream_summary_rows": list[str],  # NEW SIM-20（原始行，未拆分列）
            "component_data": list[dict],     # NEW SIM-20（MW/DENSITY 等）
            "hcurve": None,                    # 待 P5 实现
            "reactor_summary": None,           # 待 SIM-15 扩展
            "cstr_summary": None,              # 待 SIM-15 扩展
        }

    Raises:
        FileNotFoundError: 文件不存在
        ValueError: .out 缺 banner（非 PRO/II 输出）
    """
    out_path = Path(out_path)
    if not out_path.exists():
        raise FileNotFoundError(f"PRO/II .out not found: {out_path}")
    text = out_path.read_text(encoding="utf-8", errors="replace")

    banner = _parse_banner(text)
    if banner is None:
        # 容错：缺标准 banner 但含 RUN STATISTICS/STREAM SUMMARY/COMPONENT DATA
        # 任一 PRO/II 特征段，仍视为合法 .out（banner 标 unknown）
        if not any(
            marker in text.upper()
            for marker in (
                "RUN STATISTICS",
                "STREAM SUMMARY",
                "COMPONENT DATA",
                "*** CONVERGENCE STATUS",
            )
        ):
            raise ValueError(f"PRO/II .out 缺 banner 行: {out_path}")
        banner = "unknown"

    # 收敛状态
    convergence = _parse_convergence_status(text)
    convergence, unit_status_map = _parse_unit_convergences(text, convergence)

    # warnings / reactions
    warnings = _parse_warnings(text)
    reactions = _parse_reactions(text)

    # zero_flow / unreliable 需要 streams（.inp 解析；本接口仅 .out，故容错返回空）
    # 注：完整 streams 需 .inp 配合——SIM-20 dispatcher 仅 .out，调用方可走 parse_proii_files
    zero_flow = _parse_zero_flow_streams(text, {})
    unreliable = _parse_unreliable_streams(warnings, unit_status_map, {})

    # unit_ops（已有 6 类 + PUMP/HX/MIXER/FLASH/VALVE/COLUMN）
    unit_ops = _parse_unit_op_summaries_text(text)

    # column summary
    column_summary = _parse_column_summary_text(text)

    # NEW SIM-20 sections
    run_stats = _parse_run_statistics(text)
    calc_history = _parse_calculation_history(text)
    stream_rows = _parse_stream_summary_rows(text)
    comp_data = _parse_component_data(text)

    return {
        "banner": banner,
        "convergence_status": convergence,
        "warnings": warnings,
        "run_statistics": run_stats,
        "calculation_history": calc_history,
        "zero_flow": sorted(zero_flow),
        "unreliable": sorted(unreliable),
        "reactions": reactions,
        "unit_ops": unit_ops,
        "column_summary": column_summary,
        "streams": stream_rows,            # SIM-20 STREAM SUMMARY 原始行
        "stream_summary_rows": stream_rows,  # 别名（向后兼容）
        "component_data": comp_data,
        # 预留 section（本期未实现）
        "hcurve": None,
        "reactor_summary": None,
        "cstr_summary": None,
    }


def _parse_run_statistics(text: str) -> dict:
    """RUN STATISTICS 段提取（spec §3.4.2）。

    字段：
        started: str | None（HH:MM:SS MM/DD/YY）
        finished: str | None
        errors: int | None（"NO ERRORS" → 0）
        warnings: int | None（"NO WARNINGS" → 0）
        messages: str | None
        interactive_seconds: float | None
        calculations_seconds: float | None
        total_seconds: float | None
    """
    out: dict = {
        "started": None,
        "finished": None,
        "errors": None,
        "warnings": None,
        "messages": None,
        "interactive_seconds": None,
        "calculations_seconds": None,
        "total_seconds": None,
    }
    lines = text.splitlines()
    in_section = False
    for line in lines:
        upper = line.upper().strip()
        if "*** RUN STATISTICS" in upper:
            in_section = True
            continue
        if in_section:
            # 段结束：下一个 *** 开头或 OVERALL
            if upper.startswith("***") or upper.startswith("OVERALL"):
                break
            # STARTED    21:07:27 03/04/98          NO ERRORS
            stripped = line.strip()
            if stripped.upper().startswith("STARTED"):
                parts = stripped.split()
                if len(parts) >= 3:
                    out["started"] = f"{parts[1]} {parts[2]}"
                if "NO ERRORS" in stripped.upper():
                    out["errors"] = 0
                else:
                    # 20 ERRORS
                    for i, p in enumerate(parts):
                        if p.upper() == "ERRORS" and i > 0:
                            try:
                                out["errors"] = int(parts[i - 1])
                            except ValueError:
                                pass
                if "NO WARNINGS" in stripped.upper():
                    out["warnings"] = 0
            elif stripped.upper().startswith("FINISHED"):
                parts = stripped.split()
                if len(parts) >= 3:
                    out["finished"] = f"{parts[1]} {parts[2]}"
                for i, p in enumerate(parts):
                    if p.upper() == "WARNINGS" and i > 0:
                        try:
                            out["warnings"] = int(parts[i - 1])
                        except ValueError:
                            pass
            elif "NO MESSAGES" in stripped.upper():
                out["messages"] = "NO MESSAGES"
            elif "MESSAGES" in stripped.upper():
                out["messages"] = stripped
            elif stripped.upper().startswith("INTERACTIVE"):
                out["interactive_seconds"] = _parse_min_sec(stripped)
            elif stripped.upper().startswith("CALCULATIONS"):
                out["calculations_seconds"] = _parse_min_sec(stripped)
            elif stripped.upper().startswith("TOTAL"):
                out["total_seconds"] = _parse_min_sec(stripped)
    return out


def _parse_min_sec(text: str) -> float | None:
    """'6 MIN, 39.97 SEC' → 6*60 + 39.97。"""
    import re
    m = re.search(r"(\d+)\s*MIN.*?([\d.]+)\s*SEC", text, re.IGNORECASE)
    if not m:
        return None
    return int(m.group(1)) * 60.0 + float(m.group(2))


def _parse_calculation_history(text: str) -> list[dict] | None:
    """CALCULATION HISTORY 段（spec §3.4.2）。

    段内每行格式典型：'INNER  0 : E(ENTH+SPEC) = 9.077E+01'
    返回 list[dict]，每条含 {label, value}。无段返回 None。
    """
    lines = text.splitlines()
    in_section = False
    rows: list[dict] = []
    for line in lines:
        upper = line.upper().strip()
        if "CALCULATION HISTORY" in upper:
            in_section = True
            continue
        if in_section:
            if upper.startswith("***") or upper.startswith("OVERALL"):
                break
            stripped = line.strip()
            if not stripped or stripped.startswith("-"):
                continue
            # 'INNER  0 : E(ENTH+SPEC) = 9.077E+01'
            if ":" in stripped:
                label, _, rest = stripped.partition(":")
                rows.append({"label": label.strip(), "value": rest.strip()})
    return rows if rows else None


def _parse_stream_summary_rows(text: str) -> list[str]:
    """STREAM SUMMARY 段原始行列表（spec §3.4.2 PR-5 stub）。

    注：本期仅提取原始行（含 TYPE/NAME/PHASE/FROM/TO/FLOW_RATES 列），未做
    列拆分。SIM-22 PropertyConflictResolver 落地后可基于 effective
    streams 表 join；列拆分属于 P3.2 SIM-21~22 增强范围。

    容错策略：PRO/II .out 头部有 TOC（"   233   STREAM SUMMARY"），且
    第一次出现 STREAM SUMMARY 段后通常紧跟 banner + COMPONENT DATA 子段，
    不能立即算入 rows；激活条件：跳过 TOC 数字前缀并仅在看到数据行
    （FEED/PROD 前缀）或子段标头（FEED AND PRODUCT STREAMS）时确认。
    """
    import re
    lines = text.splitlines()
    rows: list[str] = []
    # TOC 行："   233   STREAM SUMMARY"（左对齐数字 + STREAM SUMMARY 单词）
    toc_re = re.compile(r"^\s*\d+\s+STREAM SUMMARY\b", re.IGNORECASE)
    # 真实段头："                  STREAM SUMMARY                    02/13/98"
    # 或独立行 STREAM SUMMARY；要求 STREAM SUMMARY 不在数字前导行中
    real_header_re = re.compile(
        r"^\s+STREAM SUMMARY\b", re.IGNORECASE
    )
    in_section = False
    in_subblock = False
    for line in lines:
        upper = line.upper().strip()
        if not in_section:
            # 跳过 TOC 行（"   233   STREAM SUMMARY"）
            if toc_re.match(line):
                continue
            # 真实段头（独立行 STREAM SUMMARY，可带日期后缀）
            if real_header_re.match(line) and not toc_re.match(line):
                in_section = True
                continue
            continue
        # in_section 之后：
        # 数据行（FEED/PROD/RECYCLE 前缀）→ 入列
        if upper.startswith(("FEED", "PROD", "RECYCLE")):
            rows.append(line.rstrip())
            in_subblock = True
            continue
        # 子段标头（FEED AND PRODUCT STREAMS / PSEUDO PRODUCT STREAMS）
        # 进入 subblock 但不入列
        if upper.startswith("FEED AND PRODUCT") or upper.startswith("PSEUDO PRODUCT"):
            in_subblock = True
            continue
        # 段结束符
        if upper.startswith("OVERALL") or upper.startswith("END OF RUN"):
            break
        if line.strip().startswith("***"):
            break
        # 子段标题/分隔/空行——忽略
        if not upper or set(upper) <= {"-", "="}:
            continue
        if in_subblock and ("PHASE" in upper or upper.startswith("TYPE") or
                          upper.startswith("----")):
            continue
        # 其他任何行——保守：仅在子段标头已出现时舍弃，避免错失
    return rows


def _parse_component_data(text: str) -> list[dict]:
    """COMPONENT DATA 段（spec §3.4.2）。

    表格行典型：'  1  H2O          LIBRARY  VAP/LIQ  18.015  998.566'
    提取 {index, name, type, phase, mw, density}。
    """
    import re
    lines = text.splitlines()
    rows: list[dict] = []
    in_section = False
    for line in lines:
        upper = line.upper().strip()
        if "COMPONENT DATA" in upper:
            in_section = True
            continue
        if in_section:
            if upper.startswith("***") and "COMPONENT DATA" not in upper:
                break
            if "STREAM SUMMARY" in upper or "OVERALL" in upper:
                break
            stripped = line.rstrip()
            if not stripped or set(stripped) <= {"-", "="}:
                continue
            # 匹配：<num> <name> <comp_type> <phase> <mw> <density?>
            m = re.match(
                r"\s*(\d+)\s+(\S+)\s+(LIBRARY|PETRO\s*CUT)\s+"
                r"(VAP/LIQ|VAPOR|LIQUID|SOLID|MIXED)\s+"
                r"([\d.]+)\s*([\d.]+)?",
                stripped,
            )
            if m:
                rows.append({
                    "index": int(m.group(1)),
                    "name": m.group(2),
                    "type": m.group(3).replace(" ", ""),
                    "phase": m.group(4),
                    "mw": float(m.group(5)),
                    "density": float(m.group(6)) if m.group(6) else None,
                })
    return rows
