"""P3.x SIM-16: COLUMN SUMMARY 解析测试。

spec §3.4.2 + audit V2.0 E-1：从 .out 的 COLUMN SUMMARY 段提取
- num_stages / condenser_type / reboiler_type
- product_streams / feed_stages
- 4 类 JSON 数据：tray_data_json / compositions_json / loading_json / rating_json

注：真实 PRO/II .out 输出因体积约束不在 fixtures 内；本测试用最小构造样例验证 lexer。
"""
from __future__ import annotations

from pathlib import Path

from app.services.proii_parser import parse_column_summary, parse_proii_out


def _write_out(tmp_path: Path, body: str) -> Path:
    p = tmp_path / "sample.out"
    p.write_text(body)
    return p


SAMPLE_OUT = """\
Generated by PRO/II Keyword Generation System V8.5

 COLUMN SUMMARY
   NAME:                  T01    MAIN
   NUMBER OF STAGES:           30    INCLUDING CONDENSER AND REBOILER
   CONDENSER TYPE:          TOTAL
   REBOILER TYPE:           KETTLE
   FEED STAGES:
     STREAM F1     STAGE 15
     STREAM F2     STAGE 22
   PRODUCT STREAMS:
     OVERHEAD    D1
     BOTTOMS     B1

 TRAY COMPOSITIONS
   STAGE  15  TEMP=350.0 K   PRES=1000.0 KPA
     C2H4  0.4000
     C2H6  0.6000
   STAGE  22  TEMP=400.0 K   PRES=1100.0 KPA
     C3H8  1.0000

 TRAY LOADING
   STAGE  15  VAPOR LOAD=0.70   LIQUID LOAD=0.50

 CONVERGENCE STATUS    CONVERGED
"""


def test_parse_column_summary_minimal(tmp_path):
    """最小 COLUMN SUMMARY 段解析：num_stages/condenser/reboiler/feeds/products。"""
    out_path = _write_out(tmp_path, SAMPLE_OUT)
    result = parse_column_summary(out_path)
    assert result["tower_uid"] == "T01"
    assert result["num_stages"] == 30
    assert result["condenser_type"] == "TOTAL"
    assert result["reboiler_type"] == "KETTLE"
    assert result["feed_stages_json"] == [
        {"stream_id": "F1", "stage": 15},
        {"stream_id": "F2", "stage": 22},
    ]
    assert result["product_streams_json"] == ["D1", "B1"]


def test_parse_column_summary_includes_tray_data(tmp_path):
    """TRAY COMPOSITIONS/LOADING 段需解析入 tray_data_json + compositions_json + loading_json。"""
    out_path = _write_out(tmp_path, SAMPLE_OUT)
    result = parse_column_summary(out_path)
    assert "tray_data_json" in result
    assert "compositions_json" in result
    assert "loading_json" in result
    # 2 个 tray（stage 15 + 22）
    tray = result["tray_data_json"]
    assert 15 in tray
    assert 22 in tray
    assert tray[15]["temp_k"] == 350.0
    assert tray[22]["pressure_kpa"] == 1100.0
    # compositions_json
    comp = result["compositions_json"]
    assert comp[15]["C2H4"] == 0.4
    assert comp[22]["C3H8"] == 1.0
    # loading_json
    load = result["loading_json"]
    assert load[15]["vapor_load"] == 0.7
    assert load[15]["liquid_load"] == 0.5


def test_parse_column_summary_returns_empty_when_no_column(tmp_path):
    """无 COLUMN 段时返回 None（spec §3.4.2：单元操作类型决定存档与否）。"""
    out_path = _write_out(tmp_path, "Generated by PRO/II V8.5\nREACTOR SUMMARY\n")
    assert parse_column_summary(out_path) is None


def test_parse_proii_out_includes_tower_summary(tmp_path):
    """parse_proii_out 顶层应暴露 tower_summaries 列表。"""
    out_path = _write_out(tmp_path, SAMPLE_OUT)
    result = parse_proii_out(out_path)
    assert "tower_summaries" in result
    assert len(result["tower_summaries"]) == 1
    assert result["tower_summaries"][0]["tower_uid"] == "T01"
