#!/usr/bin/env python3
"""Assert brief content matches plan table row for task N.

Closes OPEN-P6-6A-2 (brief template copy-paste typo guard).

Usage:
    python scripts/validate_brief.py \
        --plan docs/superpowers/plans/<plan>.md \
        --task-n 9 \
        --brief .superpowers/sdd/<plan>/task-9-brief.md \
        --expected-ids C-17 WS-CA-PR-019

Asserts every --expected-ids substring appears in the brief. Returns 0 if all
present, 1 with diagnostic message if any missing.

Background: T9 brief header read "C-18 hydrate inhibition vs WS-CA-PR-019"
(copy-paste from T10) — but PR-019 is saturation water content (C-17),
not hydrate inhibition (C-18 / PR-020). This validator catches that class
of error at controller dispatch time, before the implementer reads the brief.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Assert brief contains expected task identifiers",
    )
    parser.add_argument(
        "--plan", required=True, type=Path,
        help="Plan file (markdown table source)",
    )
    parser.add_argument(
        "--task-n", required=True, type=int,
        help="Task number to validate",
    )
    parser.add_argument(
        "--brief", required=True, type=Path,
        help="Brief file generated by scripts/task-brief",
    )
    parser.add_argument(
        "--expected-ids", required=True, nargs="+",
        help="Identifier substrings that MUST appear in brief "
             "(e.g., C-17 WS-CA-PR-019)",
    )
    parser.add_argument(
        "--foreign-ids", nargs="*", default=(),
        help="Identifier substrings that MUST NOT appear in brief "
             "(e.g., C-18 WS-CA-PR-020 — to catch cross-task copy-paste)",
    )
    args = parser.parse_args()

    if not args.plan.exists():
        print(f"FAIL: plan file not found: {args.plan}", file=sys.stderr)
        return 2
    if not args.brief.exists():
        print(f"FAIL: brief file not found: {args.brief}", file=sys.stderr)
        return 2

    brief_text = args.brief.read_text(encoding="utf-8")

    missing = [eid for eid in args.expected_ids if eid not in brief_text]
    if missing:
        print(
            f"FAIL: brief {args.brief} missing expected IDs: {missing}\n"
            f"  Plan: {args.plan} Task {args.task_n}\n"
            f"  Brief was likely generated from a different task's section "
            f"(copy-paste typo from another brief).\n"
            f"  Re-run: bash scripts/task-brief {args.plan} {args.task_n}",
            file=sys.stderr,
        )
        return 1

    foreign_hits = [fid for fid in args.foreign_ids if fid in brief_text]
    if foreign_hits:
        print(
            f"FAIL: brief {args.brief} contains unexpected foreign IDs: "
            f"{foreign_hits}\n"
            f"  These IDs belong to other tasks — copy-paste contamination.\n"
            f"  Plan: {args.plan} Task {args.task_n}",
            file=sys.stderr,
        )
        return 1

    print(
        f"OK: brief {args.brief} contains all expected IDs "
        f"{args.expected_ids} and no foreign IDs."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())